### ISSUE TITLE
Railcraft World Spikes will not accept ender pearls as fuel

### ISSUE THREAD

**Issue by SeanY2597** [xJon/Tekkit-2#100]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

A clear description of what the issue is.

Placed down Standard World Spike. open interface and attempt to place ender pearl within as fuel. This does not work and is the same for personal world spike and both world spike carts

**Comment by Lumpous** [comment]
Ender pearls are not the correct fuel for the worldspike.

Hover the input slot and it will show you what items are accepted as fuel.

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
