### ISSUE TITLE
ProjectE can cause a server crash

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#102]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable
- Log attached:
[crash-2022-09-18_13.41.45-server.txt](https://github.com/xJon/Tekkit-2/files/9593999/crash-2022-09-18_13.41.45-server.txt)
https://mclo.gs/kd1VK0V

The server crashed while just operating as normal, the player was doing normal minecraft things of chopping trees that it said caused the ticked, others were just placing blocks and I was placing dirt. 

It maybe a red herring, just out of the blue crash.

**Comment by SparksSkywere** [comment]
Another crash shortly after, a bit of asking and seeing, the player was using a red matter morning star.

[crash-2022-09-18_13.53.09-server.txt](https://github.com/xJon/Tekkit-2/files/9594006/crash-2022-09-18_13.53.09-server.txt)

**Comment by RadegasTCZ** [comment]
I have a little different problem but might be the same. I have major issue when server runs just fine and suddenly it bugs out and takes down the host machine with it. It did it on Ubuntu server, yes clean install with openjdk-8-jre installed and Windows Server 2022, also clean install using default Java 8. So I need to wait until my friend wakes up and reboots the whole computer. I see the server is kinda finicky. I might have to do some investigation myself.

**Comment by SparksSkywere** [comment]
> 

If it pulls the whole thing down, can you grab the crash logs at "tekkit-2\crash-reports", also if you are having the physical Ubuntu server crash then you need to look into why, the logs for the OS are held in "/var/log". I cannot help you find the issue with the OS as I use Windows Server 2019 on server hardware.

**Comment by RadegasTCZ** [comment]
I can look into that, it might be better to chat about it on discord where I have joined recently, since I told myself to have a chill day after I went sleep at 4AM I didn't look into it just yet, since my friend fixed RDP connection on network I can access the server now. I will get back idk if here or discord with info of what can I find.

**Comment by SparksSkywere** [comment]
> I can look into that, it might be better to chat about it on discord where I have joined recently, since I told myself to have a chill day after I went sleep at 4AM I didn't look into it just yet, since my friend fixed RDP connection on network I can access the server now. I will get back idk if here or discord with info of what can I find.
> 
> EDIT: I found one minecraft crash, but I don't think linux records stuck system.
> 
> [crash-2022-09-23_19.05.59-server.txt](https://github.com/xJon/Tekkit-2/files/9691164/crash-2022-09-23_19.05.59-server.txt)

I am not the owner of this modpack, logs and crashes if you can read the cause or need help make a new thread with the addressing the issue, Linux issues you will need to seak another forum or ask the discord, I am just a mere bug reporter to this here thread.

If you need desperate help, you can find me on the technic discord under the same name "Sparks Skywere", though responces maybe slow if I am busy!
