### ISSUE TITLE
Behavioral Issue with PESU energy output

### ISSUE THREAD

**Issue by sebollito** [xJon/Tekkit-2#104]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

After hours of experimentation and almost losing my head I think I understand how PESU are currently  behaving. So, the energy flow on the input of the PESU can be constant without problems, the output side is where the "issue" is at, it seems to be that because a PESU can output so much energy(32k EU/t) it does not push this energy on a constant manner as it should, it does so in burst, every 30 or seconds a burst of 32k EU will come through. I was able to verify this by attaching an MFSU after a series of transformers to downgrade the current to 512 EU/t. I also kept checking with an EU reader the average current that was going through the cables and transformers at different parts of the system, it always read 0 EU/t because there is no constant flow as it just jumps out of nowhere. It seems to me that this should not be the normal behavior as there is no constant flow of energy when using a PESU.

Note: I made sure to use plasma cables, 4x ins. HV cable and glass cables where they were needed after verifying their capcaity with the EU reader, also all the transformers are facing the correct way and the inputs/outputs are connected correctly as well.

Also the MFSU at the end is hooked up to a Big Flux Generator that is sending the energy from the MFSU to a big battery(Zetta Industries) that is powering up a quarry, I did it this way, so I could check the energy being produced/consumed with the EU reader(up to the MFSU of course) as there needs to be a destination for the energy for it to flow and receive a reading other than 0 EU/t.

**Comment by xJon** [comment]
Do you have enough energy stored in it to sustain 32k EU/t?

**Comment by sebollito** [comment]
Yes, at the moment of my last test if had more than 2 million EU stored.

**Comment by sebollito** [comment]
After sitting down again and redoing everything it seems that during my tests the PESU drained and couldn't keep up, just left it store 100 MM EU before starting and now it's working as inteded, so it was a mistake on my end.
