### ISSUE TITLE
Water Mill not accepting water buckets properly

### ISSUE THREAD

**Issue by lardfaktor** [xJon/Tekkit-2#108]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

I was making a water mill setup, where i am using a dispenser to fill buckets with water, a filtered importer to move the buckets to the water mills via pressure tubes and item importers to remove the empty buckets from the mills. This works perfectly fine, but when i restart the game the buckets stops entering and extracting from the water mill and i have to break and replace the water mills to function again. I tried local server and singleplayer and got the same issue, even with regular or more advanced water mills. I tested this with buildcraft's wooden transport pipe and redstone engine method and got the same results. I did not test this with other IC devices tho.
![fasz](https://user-images.githubusercontent.com/114183827/191827595-20fcb7e8-8505-4986-ba69-b56635e4f1e7.png)

**Comment by xJon** [comment]
So are you saying that after a game restart, no pipes can put buckets into the water mills?

**Comment by lardfaktor** [comment]
Yes and the importers from below wont take out the empty buckets even if i break the pipe, but from the dispenser side when i break the pipe above the importer the water buckets keeps popping up.

**Comment by Speiger** [comment]
Not sure if it is a ic2c problem.
But try out inserting from the top and then retrying.
IC2C Watermills by default only allow bucket/cell insertion only from the top by default.
(Extraction goes from any side)

Also did you install Automation Upgrades?

**Comment by lardfaktor** [comment]
I tried inserting from the top but same issue and water mills do not have any upgrade slots.

**Comment by Speiger** [comment]
@lardfaktor Automation Upgrade is inserted with a "Machine Tool" which every single IC2 Block with a Inventory has.

**Comment by lardfaktor** [comment]
@Speiger I did not know this so thanks. When i insert automation upgrade to a water mill it does the same when i restart the game, stops input and output.

**Comment by Speiger** [comment]
Ill look into it when the 1.19 version is done...
Which will be in hopefully 1-2 weeks...

**Comment by lardfaktor** [comment]
Okay, thanks for your support

**Comment by Speiger** [comment]
This should be fixed.

**Comment by xJon** [comment]
@Speiger's fix is included in `1.1.1` :)
