### ISSUE TITLE
BuildCraft's Auto Workbench doesn't support IC2C's stacked recipes

### ISSUE THREAD

**Issue by cocqvaju** [xJon/Tekkit-2#109]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Creating a "Plasma Core" from the "Industrial Craft Classic" mod in the "Auto Workbench" by "BuildCraft Factory" it doesn't work.
It consumes part of the ingredients (for example, less charged magnets than the recipe costs) but those materials disappear and there is no result. 

I image that it has to do with the need for multiple of the item in a slot when crafting and the "Auto Workbench" not playing nice with that.

**Comment by xJon** [comment]
This should be reported over https://github.com/BuildCraft/BuildCraft/issues, there's not much I can do unfortunately. Thank you nevertheless for the report!

**Comment by Speiger** [comment]
Crafting Upgrade can deal with that.
Which you can use in Machine Buffers.

**Comment by xJon** [comment]
As BuildCraft is not in active development, there's not much else I can do. It is open licensed though, so anyone could PR new improvements. Also as Speiger mentioned there are other alternatives. Will close for now!
