### ISSUE TITLE
Big Reactors >>

### ISSUE THREAD

**Issue by RedTurtleYT** [xJon/Tekkit-2#114]
I was wondering if you could please consider adding Big Reactors mod to Tekkit2, I feel a lot of people would like to use these reactors instead of the Industrial Craft ones. A large portion of the community would appreciate this mod to be added. :) 

-RedTurtleGaming

**Comment by Lumpous** [comment]
I'm sorry to say but BR generates RF whereas the modpack tries to re-create the Tekkit Classic feel.
The 2 main forms of power back then were MJ from Buildfract and EU from IC2.

BR just does not fit in the overall feel for the re-creation.
In addition the amount of generated power is way to unbalanced to fit into the pack - at least to me.
But in any case you can add it to the mods and use it either on your SP or MP.

**Comment by Speiger** [comment]
Big Reactors was one of the reasons why the RF -> EU converter were removed out of IC2C by the way.

**Comment by xJon** [comment]
Thank you nonetheless for the suggestion and feel free to add it yourself manually if you want - I believe everyone should play the game they enjoy the most :)
