### ISSUE TITLE
Clean server launches with errors

### ISSUE THREAD

**Issue by Wynadorn** [xJon/Tekkit-2#118]
**Basic details**
- **Are you using a legitimate Minecraft account?**: server
- **Are you using Java 8, 64-bit?**: yes, `jre1.8.0_341 (x64)`, on `Windows 11 (22000.978)`
- **Did you add any additional mods**: no, clean `Tekkit-2_Server_v1.0.5.zip`
- **Crash/latest log link (if applicable)**: 
    - First launch: [latest.log](https://mclo.gs/pxAp9HG) & [debug.log](https://mclo.gs/fTMNYi0)
    - 2nd launch: [latest.log](https://mclo.gs/8kokld0) & [debug.log](https://mclo.gs/L83Ls21) 

**Describe the issue**

I noticed that on start up the 1.0.5 server is generating a couple exceptions:
 - `java.lang.NullPointerException` in `zone.rong.loliasm.core.LoliFMLCallHook:call:44`
 - `java.lang.ClassNotFoundException` in `net.minecraft.world.biome.BiomeColorHelper`
 - `Invalid method structure` in `openeye.asm.injectors.ExceptionHandlerInjector.visitTryCatchBlock(ExceptionHandlerInjector.java:49)`
 - `com.google.gson.JsonSyntaxException` in `ViewEMC-1.12.2-v8.jar`'s `mcmod.info`
 - `mods.railcraft.api.core.IRailcraftModule$MissingPrerequisiteException: Thaumcraft not detected` in `railcraft-12.0.0.jar`
 - `java.io.FileNotFoundException` in `MFFS-1.12.2-4.0.1.3.jar` caused by `404` on [this url](https://bitbucket.org/SeargeDP/modularforcefieldsystem/downloads/versioninfo)
 - `com.google.gson.JsonSyntaxException` when loading the following recipes:
 - `java.lang.RuntimeException: Invalid property value detected!` in `forestry.arboriculture.blocks.PropertyTree`
 - `java.io.FileNotFoundException` in `iChunUtil-1.12.2-7.2.2.jar` caused by `404` on [this url](https://raw.githubusercontent.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/versions.json)
 - Various `Invalid list entry while Blacklisting Cargo` causing a `java.lang.IllegalArgumentException` in `railcraft-12.0.0.jar`
 - `ClassNotFoundException` caused by `pl.asie.computronics.integration.waila.IntegrationWaila`
 - Several `com.google.gson.JsonSyntaxException`s while `Parsing error loading built-in advancement`

Suppose these should be split up into separate issues.
Are other people seeing these errors too?

**Comment by xJon** [comment]
Welcome to modded Minecraft! :)
If you encounter a game breaking bug, feel free to report it in a separate issue with extra details.
Regarding these log errors - they have been for years, and still are, a part of mods (especially with cross-mod compatibility) not being _perfect_. If you are worried about them you should contact the respective mod author.

**Comment by Wynadorn** [comment]
<picture><img src="https://media.sketchfab.com/models/49efaa2c91094e4ab3c8184d2ec537a9/thumbnails/b0b040369cc541719272d827e328e643/7f49e2acb05a4beab23e908069e2ca22.jpeg" ></picture>
