### ISSUE TITLE
Crashing while opening the map

### ISSUE THREAD

**Issue by thomasflrs** [xJon/Tekkit-2#121]
The game crashed when I tried to open the large map. I tried it again later, but it worked fine the second time. Here's the crash log: https://mclo.gs/j4mrTVh

**Comment by xJon** [comment]
This seems to be a duplicate of https://github.com/xJon/Tekkit-2/issues/103 - hopefully it will get resolved in the next modpack update. Thank you nevertheless for reporting :)
