### ISSUE TITLE
Arm64 java natives for supporting Apple Silicon

### ISSUE THREAD

**Issue by Kretiss** [xJon/Tekkit-2#127]
Hello guys, is it possible to add arm64 based java natives (or how is it called) to support Apple Silicon native emulation? When I try to run modpack with Zulu Java 8 for arm64, it fails because of for example:

`'/Users/<user>/Library/Application Support/technic/modpacks/tekkit-2/bin/natives/liblwjgl.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))`

Thank you very much for your response!

**Comment by xJon** [comment]
You might want to ask about this over Technic's Discord: https://discord.com/invite/technic

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
