### ISSUE TITLE
Basalt bricks and chisel items don't like each other

### ISSUE THREAD

**Issue by DadekCz** [xJon/Tekkit-2#128]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**:  latest log here:   https://mclo.gs/Yr5mdq7

**Describe the issue**

I was playing with my brother on our server, and i was using the diamond chisel, i opened the GUI and put basalt bricks in there and the game and the server crashed.

A clear description of what the issue is.

Putting Basalt Bricks in the chisel item crashes your game (and server too)

**Comment by xJon** [comment]
I tested this on singleplayer and server and I cannot reproduce this on `1.1.0`:
![image](https://user-images.githubusercontent.com/8945347/197403812-52de823e-e44a-4d49-a672-bfaaeefd3134.png)

**Comment by DadekCz** [comment]
hmm weird, we are not using any plugins, but i changed some mod settings in quark, but i don't think it has anything to do with that, i changed client-side things like more textures for animals and stuff

**Comment by xJon** [comment]
Can you reproduce this issue on singleplayer or different servers?

**Comment by DadekCz** [comment]
I think i figured it out, i tried it again on my brother's laptop (installed a new and the same server and changed it to same configs and put in that world and hosted the server there) and it was because of that it was first time used and it's the problem, using that item gui for the first time seems like it likes to crash the primitive server, the server is so simple it doesn't handle loading some things, like once it crashed when my brother was trying it out (before he configurated it) and when loading in a volcano, the server paused and it looked like you lost connection and then the game and the server crashed, but after he re-launched it and tried it again nothing like this happend... This one is weird but it's good enough to make at least 16 people play together, simply, turns out the problem was on my side, it's the server's problem. Thanks for support, but it took me a long time to figure this out haha.
