### ISSUE TITLE
Jumping underwater resets Ambient/Environment sound level.

### ISSUE THREAD

**Issue by Jaari** [xJon/Tekkit-2#13]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No additional mods added
- **Crash/latest log link (if applicable)**: N/A

Description:
If the ambient/environment sound is set to a custom value (ranging anywhere from Off to 100%), this value is reset to 1% when moving underwater, then set back to 100% when breaking the surface of water again (no need to leave the water).

Issue initially found in the new Tekkit 2 modpack, reproduced using only Forge and Matmos, using default config. Issue not experienced when not using Matmos.

Crosspost of issue over at Matmos tracker: https://github.com/makamys/MAtmos/issues/22

**Comment by xJon** [comment]
Adding reference to the [current workaround](https://github.com/makamys/MAtmos/issues/22#issuecomment-1230413088):
> The current workaround is to set the ambient/environment volume using the "Minecraft base Ambient/Environment volume" slider in MAtmos's "Advanced options..." screen. When the game is launched or when you leave water, MAtmos sets Minecraft's slider to whatever value that slider has.

**Comment by xJon** [comment]
Closing for now.
