### ISSUE TITLE
1.1.x Server Files Request

### ISSUE THREAD

**Issue by lividsubset3** [xJon/Tekkit-2#130]
Just wondering if it would be possible to get a server update to 1.1.x. Only allowing the 1.0.5 server files

Cheers

**Comment by xJon** [comment]
You can get them from [this link](https://servers.technicpack.net/Technic/servers/tekkit-2/Tekkit-2_Server_v1.1.0.zip).

**Comment by lividsubset3** [comment]
@xJon Perfect thank you sir.
