### ISSUE TITLE
[Mod] IC2 Classic - Update to 1.5.6.0

### ISSUE THREAD

**Issue by lividsubset3** [xJon/Tekkit-2#131]
Hey, 
Just wondering if it would be possible to update IC2 to [1.5.6.0](https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/4048720). 
The mod creator updated it to allow the steam reactor to have its own config for power change. (output more steam, and use more water) I think it would be a nice update, as since you recently changed the output of the normal reactor.

Cheers

**Comment by xJon** [comment]
It is a useful update, with a lot of useful fixes! Not sure about the steam output change though, as from testing it seems that the current output already maxes out multiple turbines.
It will be updated as soon as we can fix the current issue with Railcraft :)

**Comment by lividsubset3** [comment]
Yes that's true. The steam reactor takes in water and outputs steam. But the config allows for change of steam output. 
For example if you use one quad blaze fuel rod it will use a total of 17.3 steam turbines.
Would be wonderful if steam was x2 as powerful then reactor. And would be more enjoyable to build that infrastructure for steam.

**Comment by xJon** [comment]
When you say "x2 as powerful", do you mean in steam production? isn't 17 turbines already quite high?

**Comment by xJon** [comment]
Updated in `1.1.1` :)
