### ISSUE TITLE
Minecraft failed to start. Tekkit 2 with Optifine

### ISSUE THREAD

**Issue by Misqudestrojer** [xJon/Tekkit-2#132]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes OptiFine_1.12.2_HD_U_G5
- **Crash/latest log link (if applicable)**:[ link to log / not applicable](https://mclo.gs/rUDYrIp)

**Help needed**

People say that manually installing Optifine is ok and it works. For me it worked for one day. Next day minecraft won't launch with optifine.
Any ideas how to figure it out?

![image](https://user-images.githubusercontent.com/38586390/198696285-5e0a35d5-446d-4b50-9953-209c73533817.png)

**Comment by xJon** [comment]
Did you mean to close the issue?

**Comment by Misqudestrojer** [comment]
yes
