### ISSUE TITLE
Crafting Table IV doesn't support certain recipes

### ISSUE THREAD

**Issue by kilobit123** [xJon/Tekkit-2#133]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Crafting Table IV doesn't let me craft certain recipes. This affects most of IndustrialCraft and EnderStorage. An example is the Machine Block.

**Comment by xJon** [comment]
This is somewhat of a known issue and unfortunately the mod is not in active development. Either way, it might be beneficial if you report this directly to the mod author over https://github.com/Elecs-Mods/CraftingTable-IV/issues

**Comment by xJon** [comment]
Closing this for now, thank you for the report nonetheless!
