### ISSUE TITLE
Config Balance Request: Balance the steam output of nuclear steam reactors

### ISSUE THREAD

**Issue by SHexplorer** [xJon/Tekkit-2#134]
I am using nuclear steam reactors to produce energy and I think they are not balenced. A normal nuclear reactor produces 15eu/t with one uranium cell and one heat vent. A nuclear steam reactor produces 15 to 16mb/t of steam with one uranium cell and one steam vent. With this 15mb/t a basic steam turbine from ic2 produces 9eu/t. So normal nuclear reactor are much more efficient than nuclear steam reactors. 

In my opinion nuclear steam reactors should produce more steam per tick so the power output with a steam turbine (ic2 or railcraft) is 25% to 30% more than normal nuclear reactors because steam reactors require more materials, need water and a additional steam turbine to produce power. So maybe you can increase the steam per tick rate in the ic2 config so nuclear steam reactor have an advantage over normal reactors (otherwise their use make no sense).

Thx

**Comment by Speiger** [comment]
@SHexplorer for the normal uranium the reduced or equal power output is valid.
Since the output is based on the heat output, not on the "active production".
Meaning a normal uranium rod isn't as good in a steam reactor, while others are better.

In 1.19.2 we actually double the output and increase the total max potential output (not a straight buff) by 50% too.
But there is also a cap of how much power you can produce.

So a single normal rod producing less is reasonable IMO.

What i would suggest with the steam reactor that you go with blazing uranium, since that produces a lot more heat then normal uranium, ergo producing more steam per tick.

**Comment by xJon** [comment]
I did not actually include a buff to `energyGeneratorSteamReactor` in version `1.1.1` of the modpack but like Speiger mentioned it is a sound suggestion overall.

**Comment by SHexplorer** [comment]
Well, okay thank you for that explanation @Speiger. I only noticed that with 1.1.1 or 1.1.0 the nuclear power production was increased (like mentiond in the changelog) and the nuclear steam to power production not, I thought it was just forgotten to adjust it too. (in 1.0.5 it was 5 eu/t per cell while in steam reactors it stayed 9eu/t with the basic turbine).

But okay, I understand the concept of steam reactors now and why they are not just a "better" reactor than normal nuclear reactors. I just thougt it make sense since when using an seperate power production of steam and turbines it is more efficient than an all-in-one system as normal nuclear reactor.

I just wanted to report it here if it was like discribed forgotten to adjust. You can close this issue if you want. Thanks

**Comment by xJon** [comment]
@SHexplorer I'm considering doubling the `energyGeneratorSteamReactor` value in `\config\ic2\ic2.cfg` like @Speiger mentioned was done in future versions. What do you think?

**Comment by SHexplorer** [comment]
That would be 25% more output than the normal nuclear reactor (19eu/t, normal reactor 15eu/t). That would be my suggestion/wish. But I also understand when it is designed to not put out more power with normal cells like @Speiger mentioned above. Your call @xJon

**Comment by xJon** [comment]
@SHexplorer But even then with a full sized steam reactor, would you truly be able to output more power than a normal reactor? Wouldn't the amount of turbines you need be over a thousand?

**Comment by SHexplorer** [comment]
I dont know the save maximum power output of a normal nuclear reactor but with some railcraft steam turbines you could get a lot of power. Every turbine puts out 220eu/t. They are not cheap but you can drive (with the current setting) 4 Turbines and more from a single full sized steam reactor (i just testet it normal uranium cells and overclocked steam vents) without active cooling, so produce over 1000eu/t easily, but are also more dangerous when the steam is not removed from the reactor in time.

I personally just like the concept which is more realistic to the normal world and need more planning and build time for the hole system. I think with doubling the output it becomes a bit overpowerd but otherwise it a normal reactor is just cheaper and puts out more power in relation to nuclear steam reactors.

**Comment by xJon** [comment]
@SHexplorer If that's the case I think I'll double it per @Speiger's suggestion. Thank you for the input!

**Comment by xJon** [comment]
Changed in `1.1.2` :)
