### ISSUE TITLE
crash happening due to bottom valves on tanks

### ISSUE THREAD

**Issue by Blacksail-1** [xJon/Tekkit-2#135]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log (at bottom of issue) X3

**Describe the issue**

A clear description of 

what the issue is.
When I build a tank to store liquid (iron or steel) and click the bottom set of valves on the underside it causes the game to crash
 with an UNKNOWN error. at first I wondered what caused the crash to happen but after testing the other areas where the valves were at and not getting a crash i narrowed it down to those on the bottom of the tanks. it only happens if you physically click them. doesn't happen if you connect stuff to them (from another pipe to the valve but will happen if you try to connect it from the valve to the pipe.)

https://mclo.gs/vVModro

https://mclo.gs/cT2eS4L

[crash-2022-10-30_13.27.33-client.txt](https://github.com/xJon/Tekkit-2/files/9895959/crash-2022-10-30_13.27.33-client.txt)

[crash-2022-10-30_13.15.44-client.txt](https://github.com/xJon/Tekkit-2/files/9895963/crash-2022-10-30_13.15.44-client.txt)

[crash-2022-10-30_13.11.34-client.txt](https://github.com/xJon/Tekkit-2/files/9895964/crash-2022-10-30_13.11.34-client.txt)

**Comment by xJon** [comment]
Thanks for the report!
As a workaround, a bottom layer valve on the side does not crash and can still function as an output valve.

**Comment by Blacksail-1** [comment]
been using that now since i found that bug. thought i would mention the crash with the bottom layer valves, rather be it me bring it up now than someone else later.

**Comment by xJon** [comment]
This is fixed in `1.1.3` thanks to @ACGaming's [patch](https://github.com/ACGaming/Quark/commit/9325b5f608d6ccc712d18de36f26a796f4ec6644) :)
