### ISSUE TITLE
Logistics Pipes Crafting

### ISSUE THREAD

**Issue by Mccaw100** [xJon/Tekkit-2#136]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**:  / not applicable

**Describe the issue**

Logistics crafting pipes no longer Function in part of a system.  They allow you to connect them to a system and power is passed through them and on to the rest of the system. You can connect them to the Crafting tables and import in to the pipe as normal. Once this is done it will show list of available crafts on your remote orderer. However if you attempt to craft the item it will craft one and then the pipe will stop functioning, still show that it is in place but is invisible  and no longer sends power through the system.

**Comment by xJon** [comment]
What modpack version are you playing with?

**Comment by Mccaw100** [comment]
Hi xJon this is 1.1.2 - Unsure how to get the Game log as it doesnt crash?

**Comment by xJon** [comment]
You can get the game log through the modpack's installation folder -> `\logs\latest.log`

**Comment by Mccaw100** [comment]
Yes this was completely fine until this new update 2 days ago.

https://mclo.gs/FXMr87U

**Comment by xJon** [comment]
You need to open the `latest.log` file and copy over its contents to https://mclo.gs/ :)

**Comment by Mccaw100** [comment]
https://mclo.gs/slL4fKW Apologies that should be it

**Comment by xJon** [comment]
Is this from a session in which the issue has occurred? I don't seem to see any error from Logistics Pipes unfortunately.

**Comment by Mccaw100** [comment]
Hi - recreated the issue and refreshed should have occurred between 00:56-00:57

https://mclo.gs/7o1Feha

**Comment by xJon** [comment]
I can see an issue there... but it seems you are playing on a server. Any chance you can share the server-sided log? Or alternatively reproduce the issue on a singleplayer world and share your log then?

**Comment by Taliviere** [comment]
The server side logs are 
https://mclo.gs/yoLfUeE
Thank you so much for the assistance

**Comment by xJon** [comment]
Thank you for the report! I'll forward this to the mod developer :)

**Comment by Mccaw100** [comment]
Fantastic Thankyou!

**Comment by xJon** [comment]
Could you send the full server log from when the issue occurred?

**Comment by Rishum-P** [comment]
On our server, we have not been having this issue. Everything crafts fine across a very significant amount of large logistics crafting systems. It's likely isolated to their server and Fake Players, perhaps.

**Comment by AngryCarrot789** [comment]
I feel like this is due to using SpongeForge server side

**Comment by xJon** [comment]
@Mccaw100 Perhaps you could check whether you can reproduce the issue on singleplayer or unmodified server? In case it is caused by a conflict, you could fetch the extra information to try to troubleshoot it.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
