### ISSUE TITLE
[BUG] IC2 Furnace (electric & induction) cant smelt "normal" items

### ISSUE THREAD

**Issue by KreXTV** [xJon/Tekkit-2#138]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: yes on client (nitrado server default setting is java 7, just saying, but tested on client and server)
- **Did you add any additional mods**: no (just _optifine_)
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Electric furnace & induction furnace cannot burn normal items like cobblestone, sand or food. You can't put many items in it.
Copper Dust, for example, does work.

**Comment by xJon** [comment]
Thanks for the report! It is a known issue and hopefully will get resolved soon (https://github.com/TinyModularThings/IC2Classic/issues/493).

**Comment by KreXTV** [comment]
thank you for your quick feedback!

**Comment by xJon** [comment]
Resolved in `1.1.3` thanks to @Speiger's update :)

**Comment by xJon** [comment]
Issue is back in `1.2.0`. Hopefully will be resolved next week.

**Comment by xJon** [comment]
Resolved again in `1.2.1` thanks to @Speiger's update :)
