### ISSUE TITLE
Steam Engines Railcraft

### ISSUE THREAD

**Issue by IcarusPines** [xJon/Tekkit-2#140]
Are the steam engines disabled? When serching ingame they appear in jei but i get no recipe and when i cheat the engines i cant get them to work or enter the interface(i belive they have one...).
When looking in the Confic data the recipies are enabled disableling restarting enabeling and restarting dosnt work either.
Answer would be appreciated.

**Comment by xJon** [comment]
Thanks for pointing this out! It actually makes sense, as MJ is disabled in the pack and BuildCraft uses RF (if you want to revert this feature you could remove `buildcraftfluxified-1.0.0.jar`).
I'll hide them from JEI in future updates to hopefully make it clear that they are disabled.

**Comment by IcarusPines** [comment]
Is it possiple to change their output from MJ to RF?

**Comment by xJon** [comment]
I do believe there are multiple other options in the pack that generate RF with steam - e.g. Railcraft's Steam Turbine.
I'm not sure about their output, I couldn't find such option.

**Comment by IcarusPines** [comment]
The Steam Turbine outputs EU nor rf...

**Comment by IcarusPines** [comment]
not*

**Comment by xJon** [comment]
Oh you are right - my bad. You can always use Flux Generators to convert the EU to RF though, in general it is encouraged to always generate EU in the modpack as it's a more balanced power system.
