### ISSUE TITLE
'Updating screen events' crash with Logistics Pipes

### ISSUE THREAD

**Issue by 1idenburg** [xJon/Tekkit-2#141]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/PaMvkPR

**Describe the issue**

Fresh install of 1.1.3, pressing the '!' icon of upgrades in the 'Upgrades' section of the pipe manager (in my case used on a crafting pipe) causes a crash, with the the pipes connection to machines/other pipes rendering for a split second before crashing. Only tried on disconnection and sneaky upgrades, but since I suspect the crash has to do with that render it should crash for all of others too.

**Comment by xJon** [comment]
Seems to be https://github.com/RS485/LogisticsPipes/issues/1674? Hopefully it'll get resolved on the mod's end, then eventually included in a future modpack update. Thank you for the report :)

**Comment by 1idenburg** [comment]
> Seems to be [RS485/LogisticsPipes#1674](https://github.com/RS485/LogisticsPipes/issues/1674)? Hopefully it'll get resolved on the mod's end, then eventually included in a future modpack update. Thank you for the report :)

Yep, also posted it there. Hopefully it'll get resolved soon :)

**Comment by 1idenburg** [comment]
@xJon bziemons just fixed it. hope to see it in the next update.

**Comment by xJon** [comment]
Sweet! Will be included in the next modpack update (for now you can feel free to manually update the mod).

**Comment by xJon** [comment]
Apologies for the delay - should be fixed in version `1.2.0` of the modpack!
