### ISSUE TITLE
"server must have hei installed"

### ISSUE THREAD

**Issue by MulaHwaka** [xJon/Tekkit-2#143]
Have a server running off of my pc and friends can connect with no issue. But HEI was preventing us from crafting anything modded. Vanilla tools could be made but anything that was from a mod wouldn't sohw up as a craft output when the materials were put into the table. Hovering over the plus icon that would auto input the material in the correct pattern would show the message "server must have hei installed" and could not be selected. Checked the server and it had HEI in and as the same version as was running on client. Tried removing HEI and replacing with JEI but got the same result, just the message changed to say "server must have jei installed". Same issue for both me connecting locally and for friends connecting with port-forwarding.

**Comment by xJon** [comment]
Are you starting the server using the launch script?

**Comment by MulaHwaka** [comment]
Yup, the .bat file

**Comment by xJon** [comment]
Did you modify the server in any way?

**Comment by MulaHwaka** [comment]
Yep, figured out what I had done wrong before, had switched the .bat to point at the server.jar not the forge.jar, because the server wasn't launching via the forge.jar file, instead I get this in the console
https://i.imgur.com/zQZYH7o.png
for the image above it's a fresh server install, haven't done anything except run the LaunchServer.bat file.

**Comment by ACGaming** [comment]
Please make sure that you‘re using the latest Java 8 64-bit to run the server.

**Comment by MulaHwaka** [comment]
Updated Java and new fresh server install, same result
https://i.imgur.com/K5AYPG0.png

**Comment by MulaHwaka** [comment]
Damnit, I had jdk 19 installed. It wasn't showing up in the Java uninstall tool but was affecting the server launch. Thanks for the help
