### ISSUE TITLE
Industrial Craft Classic requiring at least 2 of some upgrades to take effect

### ISSUE THREAD

**Issue by Blaze1499** [xJon/Tekkit-2#145]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Tried putting a single overclocker upgrade into various tier 1 ICC machines, (Macerator, Compressor, Extractor, Electric furnace), and despite having plenty of power in my MFE, saw no speed increase on any of these machines. According to the wiki, the macerator should have its processing time reduced from 20 to 14 sec/item, but i saw no such increase. I also tried a Muffler upgrade in a rotary macerator and heard no reduction in noise

**Comment by xJon** [comment]
Can you forward that report to https://github.com/TinyModularThings/IC2Classic/issues ?

**Comment by Blaze1499** [comment]
Done

**Comment by xJon** [comment]
Should be fixed in version `1.2.0` of the modpack :)
