### ISSUE TITLE
Railcraft's Steel Anvil broken UI elements

### ISSUE THREAD

**Issue by Misqudestrojer** [xJon/Tekkit-2#146]
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes: optifine, Inventory spam
- **Crash/latest log link (if applicable)**:  not applicable

When entering steel anvil I can't see item description while hovering cursor on it (enchanted books which I want to merge in anvil).
It works on iron anvil.

Stell anvil
![image](https://user-images.githubusercontent.com/38586390/204381090-8c28ee26-01e8-406c-9f87-a446ba923c8c.png)
Iron anvil
![image](https://user-images.githubusercontent.com/38586390/204381379-cb0bd717-de94-4391-a05a-d6f55ea2ffa3.png)

**Comment by xJon** [comment]
Can you forward this report to https://github.com/Railcraft/Railcraft/issues ?

**Comment by Misqudestrojer** [comment]
Ye, I'll try

**Comment by xJon** [comment]
Fixed in version `1.2.0` of the modpack thanks to @ACGaming :)
