### ISSUE TITLE
Radioactive Bees from Binnie's Extra Bees don't have IC2 Classic compatibility

### ISSUE THREAD

**Issue by HalfBakedTurkey** [xJon/Tekkit-2#147]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / **yes**
- **Are you using Java 8, 64-bit?**: no / **yes**
- **Did you add any additional mods**: yes (detail) / **no**
- **Crash/latest log link (if applicable)**: link to log / **not applicable**

**Describe the issue**
After getting quite far with the forestry bees it became apparent to me that one of the most useful late game bees the radioactive ones do not produce the radioactive comb which I am playing on single player so this is something I can fix, but it is an issue none the less and honestly there are not a whole lot of other very useful bees so I would consider it a major issue lmao but not game threatening at all.
![Evidence](https://user-images.githubusercontent.com/119465001/204682404-dd8328a7-fbfa-4030-b215-37b54ca4dd30.PNG)

**Comment by xJon** [comment]
Thank you for the report! Will look into resolving this :)

**Comment by xJon** [comment]
Fixed in version `1.2.0` of the modpack thanks to @ACGaming :)
