### ISSUE TITLE
Placing Aluminum Wire next to IC2 Classic machine can lag the game

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/Tekkit-2#15]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
Title and video are self explanatory
https://streamable.com/e/u6im8h

**Comment by xJon** [comment]
Thanks for the report! This is a known issue with Galacticraft (https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/30#issuecomment-1193140906), and would only happen if the wires are placed next to IC2C machines. Hopefully they will be able to fix it in the future.

**Comment by xJon** [comment]
I also opened now a new issue for this over their repository: https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/90

**Comment by xJon** [comment]
Resolved in `1.0.1` thanks to @ACGaming :)
