### ISSUE TITLE
Pocket Crafting table causes game to crash

### ISSUE THREAD

**Issue by GamerMan27** [xJon/Tekkit-2#151]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/ISjiy0a

**Describe the issue**

I tried to use the pocket crafting table. Any time I use it the game crashes. Specifically, my inventory was full except the crafting grid, and I tried to craft 16 snow blocks.

**Comment by GamerMan27** [comment]
If that wasn't the crash log, I don't know where it would be. Can you tell me the relative location? I'll look there.

**Comment by xJon** [comment]
Inside the `crash-reports` folder.

**Comment by xJon** [comment]
I was able to reproduce it :)

**Comment by xJon** [comment]
Closing as the mod is not currently in development.

**Comment by xJon** [comment]
@asiekierka decided today is the day. The fix will be included in the next modpack update!

**Comment by CyberGaming424** [comment]
Still having this issue...

**Comment by xJon** [comment]
@CyberGaming424 Can you share your crash log?

**Comment by CyberGaming424** [comment]
`java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925) ~[?:1.8.0_51]
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1592) ~[?:1.8.0_51]
	at javax.imageio.ImageIO.write(ImageIO.java:1520) ~[?:1.8.0_51]
	at silly511.backups.helpers.BackupHelper.backup(BackupHelper.java:84) ~[BackupHelper.class:?]
	at silly511.backups.BackupManager$BackupThread.run(BackupManager.java:223) [BackupManager$BackupThread.class:?]
[13:28:12] [Server thread/INFO] [backups]: Restoring world saving`
Went back through the log and this was the last thing it spit out.

**Comment by CyberGaming424** [comment]
How to recreate, use inventory tweaks while in pocket crafting bench

**Comment by xJon** [comment]
Should be fixed in `1.2.4`, although unfortunately there are other unresolved edge-cases that can cause issues.
