### ISSUE TITLE
RocketMode UI missing when using Advanced Nano Chestplate

### ISSUE THREAD

**Issue by mcchallenger** [xJon/Tekkit-2#152]
- Are you using a legitimate Minecraft account?: yes
- Are you using Java 8, 64-bit?: yes
- Did you add any additional mods: no

When activating rocket mode using the Advanced Nano Chestplate, the UI that normally goes over the experience bar which tells you the charge % does not appear. Instead, nothing happens and it shows the normal xp bar

**Comment by xJon** [comment]
Where are you familiar with this feature from? I don't see it happening even when playing only with minimal mods.

**Comment by mcchallenger** [comment]
> Where are you familiar with this feature from? I don't see it happening even when playing only with minimal mods.

Hi Jon, here I'm in a single player world with default tekkit 2

This is after equiping the Advanced Electric Jetpack and activating RocketMode
![image](https://user-images.githubusercontent.com/87624613/208026407-ee16d4b7-aba1-4101-b70f-1408086e30dd.png)

Here is doing the same but with the Advanced Nano Chestplate Equipped
![image](https://user-images.githubusercontent.com/87624613/208026802-7fffce82-e569-48c5-8f55-cf2990a0c635.png)



Also, it seems like there is another bug with both the electric and nano versions where holding down left or right click and pressing the "Mode Switch Key" will start an endless cycle of toggling the jetpack on and off (this can be interrupted by hitting the "Toggle Key").

Hope this helps!

**Comment by xJon** [comment]
Thanks for the clarification! In this case that missing feature / bug is on the mod's end (and the same goes for the other issue you mentioned).
It'd be really helpful if you can write about both over https://github.com/Trins-mods/Gravisuit-Classic-Edition/issues :)

**Comment by xJon** [comment]
Closing this due to https://github.com/Trins-mods/Gravisuit-Classic-Edition/issues/23, but assuming the mod does introduce this feature in the future the modpack will be updated to include it :)
