### ISSUE TITLE
Tekkit says ram full? Maybe stuck on rendering dirt?

### ISSUE THREAD

**Issue by edjodapro** [xJon/Tekkit-2#154]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: / no
- **Crash/latest log link (if applicable)**: link to log 
https://mclo.gs/NvZvhBy

**Describe the issue**

A clear description of what the issue is.
My tekkit world crashed and now when I open it it crashes without letting me in and shows me this link.

**Comment by xJon** [comment]
Did you try allocating more RAM?
How much RAM do you have on your computer?

**Comment by edjodapro** [comment]
had to reinstakl java
