### ISSUE TITLE
Item Importers/Filtered Item Importers won't pull items out of IC2C Machines.

### ISSUE THREAD

**Issue by portalsam1** [xJon/Tekkit-2#155]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Item Importers/Filtered Item Importers will not pull out of any IC2C machines from any side even though pressure tubes can put items into them. I am unsure if this is intentional or not as I can not find any information about it.

https://user-images.githubusercontent.com/41414314/209401121-69b542bd-0999-4563-9697-5be7dbf99814.mp4

**Comment by xJon** [comment]
Did you configure the upgrades? You can read about them over: https://github.com/TinyModularThings/IC2Classic/wiki/Machine-Upgrades#basic-import-upgrade

**Comment by portalsam1** [comment]
I don't believe that's relevant. The machine in question can already import items from pipes with no upgrades. But Item Importers themselves will not pull out of it which makes no sense when something like BuildCraft pipes can.

**Comment by xJon** [comment]
Can you explain to me how did you use/install the upgrades after crafting them?

**Comment by portalsam1** [comment]
I'm not using any upgrades. I am referring to RedPower Item Importers not the Import Upgrade.

**Comment by xJon** [comment]
Oh, I'm really sorry about the misunderstanding. I tried reproducing this whilst outputting from the bottom and it seems to work:
![image](https://user-images.githubusercontent.com/8945347/209439534-12aad6b7-b3e9-48f9-b3f5-e93a9bac7f54.png)

**Comment by portalsam1** [comment]
Oh that seems to work although it was a bit misleading, thanks.

**Comment by xJon** [comment]
I think that in order to output from any direction, the machine needs one of these - https://github.com/TinyModularThings/IC2Classic/wiki/Inventory-Upgrades
