### ISSUE TITLE
Stuck in GalacticCraft map

### ISSUE THREAD

**Issue by Hendo0** [xJon/Tekkit-2#156]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: 
-  not applicable

<!--
When using the command dimension tp it takes you to the galactic map, but it locks you in this screen. No button closes the map and when restarting my game, it loads me on with the map still open and uncloseable, please help me, my tekkit world is currently unplayable.

**Comment by Hendo0** [comment]
When using the command dimension tp it takes you to the galactic map, but it locks you in this screen. No button closes the map and when restarting my game, it loads me on with the map still open and uncloseable, please help me, my tekkit world is currently unplayable.

**Comment by Hendo0** [comment]
When using the command dimension tp it takes you to the galactic map, but it locks you in this screen. No button closes the map and when restarting my game, it loads me on with the map still open and uncloseable, please help me, my tekkit world is currently unplayable.

**Comment by Hendo0** [comment]
![Uploading image.jpg…]()

**Comment by xJon** [comment]
Which command are you talking about?

**Comment by Hendo0** [comment]
> Which command are you talking about?

/dimension tp or somthing.

**Comment by xJon** [comment]
Can you not click on Earth and "Launch"?

**Comment by Hendo0** [comment]
> Can you not click on Earth and "Launch"?

Oh yes thank you so much that has worked, I thought I needed a rocket to press that but no I have escaped the menu! Thank you sir.
