### ISSUE TITLE
Non-Legacy Galacticraft

### ISSUE THREAD

**Issue by Freggles2401** [xJon/Tekkit-2#157]
Why make us use legacy galacticraft? Dont give us the wacky 4.0.4. or w/e the fuck it is.

**Comment by xJon** [comment]
Galacticraft for Minecraft 1.12.2 is marked as "Legacy" because they are working a rewrite for a future version of Minecraft.
Tekkit 2 uses the latest Galacticraft version that's available (and actually finished).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
