### ISSUE TITLE
I cant join my friend's server when other people can, the server icon doesnt even switch to the tekkit icon

### ISSUE THREAD

**Issue by Fernuzs** [xJon/Tekkit-2#158]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / yes
- yes
- **Are you using Java 8, 64-bit?**: no / yes
- yes
- **Did you add any additional mods**: yes (detail) / no
- no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Help needed**

A clear description of what help is needed.

**Comment by xJon** [comment]
Can you attach a log or screenshot of the error?

**Comment by xJon** [comment]
Closing due to missing information (will reopen if requested)!
