### ISSUE TITLE
Forestry: Electrical Engine bug when connecting to an extraction pipe

### ISSUE THREAD

**Issue by Nyun0** [xJon/Tekkit-2#159]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Forestry's _Electrical Engine_ has a bug - when attached to an extraction (e.g. wooden) pipe - extracted items are tried to be inserted into the _Electrical Engine_ itself. The engine cannot accept them, so they are spilled all over. BuildCraft's engines (_Redstone_, _Stirling_, _Combustion_) do not connect to an extraction pipe, and the _Electrical Engine_ from the Forestry shouldn't as well.

The problem is clearly visible on the attached screenshots:

![2023-01-13_03 23 02](https://user-images.githubusercontent.com/44881234/212222683-e082dafc-9d14-481f-9f59-fd30387536e2.png)

![2023-01-13_03 27 12](https://user-images.githubusercontent.com/44881234/212223084-411c8ee3-b8f0-4be0-80fa-545209854093.png)

![2023-01-13_03 27 46](https://user-images.githubusercontent.com/44881234/212223115-e6ec7832-b24f-42c8-801f-bf69fd3b284f.png)

**Steps to reproduce**:
1. Place a chest.
2. Place 10 stacks of whatever item in it.
3. Connect it with a _Wooden Transport Pipe_.
4. Place a _Recycler_ at the end of a transport pipe (we're extracting from the chest to the _Recycler_).
5. Place an _Electrical Engine_ to power the transport pipe. **At this point the engine connects with the pipe that has been already connected with the _Recycler_**!
6. Attach any kind of power to the engine (e.g. _Glass Fibre Cable_ from a fully charged _MFE_).
7. Start the engine using a redstone signal (e.g. place a _Lever_ on it's back and activate it).
8. Watch the stuff from the chest being pulled out extremely fast and getting spilled all over.

**Comment by Nyun0** [comment]
I see it was already mentioned long ago: https://github.com/ForestryMC/ForestryMC/issues/2681

**Comment by xJon** [comment]
Thank you for the report! Unfortunately Forestry is no longer in development, so I'm not sure if this is going to be fixed. That being said, there are multiple workarounds to this - the first could be using Flux Generators instead in order to convert EU to RF. The other workaround would be to use Flux Cables between the Forestry engines and the extraction pipe.
