### ISSUE TITLE
Game is stuck on a save from hours ago.

### ISSUE THREAD

**Issue by JackGal1** [xJon/Tekkit-2#160]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / yes  YES
- **Are you using Java 8, 64-bit?**: no / yes  YES
- **Did you add any additional mods**: yes (detail) / no  NO
- **Crash/latest log link (if applicable)**: link to log / not applicable NOT APPLICABLE

Just played for an hour and a half and i quit to the main menu with the proper exit button and nothing saved when i reloaded in. When I go to the backups I can see my saves from about 20 minutes ago and i load them and it just takes me back even further from that. Its like no matter what save / backup it loads me so far back

**Comment by JackGal1** [comment]
I can give more info If asked but im not really sure what else to post / explain. All my backups from today load to the point in where i first started today and all my other backups from yesterday work

**Comment by xJon** [comment]
Can you share the latest log from that session using a [paste-tool](https://mclo.gs/)? Perhaps there were some errors preventing your world from saving.

**Comment by xJon** [comment]
Closing due to missing information (will reopen if requested)!
