### ISSUE TITLE
No way to charge the Multi-tool wrench from Mffs and no way to pick up the mffs and other related items after pick up

### ISSUE THREAD

**Issue by blakerocks81** [xJon/Tekkit-2#163]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / yes yes
- **Are you using Java 8, 64-bit?**: no / yes yes
- **Did you add any additional mods**: yes (detail) / no no 
- **Crash/latest log link (if applicable)**: link to log / not applicable na

**Describe the issue**

A clear description of what the issue is.

i have placed down an mffs and mffs capacitor with no way to pick them up since the wrench from the mod does not have a way to charge it.

**Comment by xJon** [comment]
You can charge the wrench using a capacitor and an extractor with Forcicium :)

**Comment by blakerocks81** [comment]
awesome thank you for the help i was stuck and getting frustrated with it haha
