### ISSUE TITLE
ProjectRed Rendering Item Crash on Launch

### ISSUE THREAD

**Issue by cozytrash** [xJon/Tekkit-2#164]
**Basic details**
- **Are you using a legitimate Minecraft account? YES
- **Are you using Java 8, 64-bit?**: NO (i assume that might be the issue)
- **Did you add any additional mods NO
- **Crash/latest log link (if applicable)**: https://mclo.gs/HFsbEwR

**Help needed**

I am new to Tekkit and to the modding community in general so forgive my lack of know-how. My game was running fine and smoothly when I was suddenly crashed while building a house. The item that had trouble rendering was a ruby pickaxe from projectred, which I had no issues with up until today. The crash report linked is the first one I received telling me their may be issues with hammercore, Forge and the launcher, and one other. The second report I received claimed it was an unknown issue with the same walkthrough and no description. I can link this report as well if it would be helpful. I would be grateful for any help/advice as to how to fix this issue. Thank you!

**Comment by ACGaming** [comment]
`java.lang.OutOfMemoryError: Java heap space`
You need to allocate more RAM, 2GB is not quite enough.

**Comment by xJon** [comment]
Thanks to this issue I've increased the minimum from 2.5 GB to 3 GB (as I saw you weren't using any resource packs or Optifine).
