### ISSUE TITLE
[Industrial Craft Classic] Wave Generator drops output when away from it

### ISSUE THREAD

**Issue by Nyun0** [xJon/Tekkit-2#165]
I have a question (potentially a bug) regarding **Wave Generator**. I have created 7 Wave Generators and placed them (height: 62) next to each other.
![2023-01-24_12 14 32](https://user-images.githubusercontent.com/44881234/214278318-07ab34b4-301c-4bc4-8a70-f3f0ca8853aa.png)

Then I have connected them above using _Glass Fibre Cable_. Placed an _MFSU_ to gather the produced EU and linked it with yet another _MFSU_, where the latter is connected with _Mass Fabricator_.
![2023-01-24_12 14 57](https://user-images.githubusercontent.com/44881234/214278497-6171b59e-6cde-4289-8ce6-6b4883cd5ecf.png)

The problem I am experiencing is that if I am moving away from them (e.g. I go over the height of 72) the output of those generators drops drastically.
![2023-01-24_12 17 04](https://user-images.githubusercontent.com/44881234/214283780-5eb3767d-724b-4ac8-ab48-b3418d6fc060.png)

It is very easy to notice by looking at the _MFSU_ place near the generator - when I am standing on it I see that the unit is filled with EU really fast, despite constant flow to the _Mass Fabricator_.
![2023-01-24_12 43 25](https://user-images.githubusercontent.com/44881234/214283420-9eb53423-5190-4af9-a930-223a7efa66c7.png)

and when I am above 10 blocks of the generators the EU is not filling up that fast:
![2023-01-24_12 43 58](https://user-images.githubusercontent.com/44881234/214283857-ed02a4b1-a6b8-4984-a4b9-b41fc28e9bab.png)

The question is - **is this by design** (unfortunatelly finding anything, any kind of wiki, on the internet regarding Wave and Ocean Generators is next to impossible - the only official IC wiki page explains very litte with not much details) **or is it simply a bug?** Placing _World Spike_ next to the generators does not help at all (plus, 10 blocks length is a lot less than 10 chunks, which I believe is the lenght around the player to keepalive the items etc.)

**Comment by xJon** [comment]
This is the official wiki - https://github.com/TinyModularThings/IC2Classic/wiki
We can also ask @Speiger about this.

**Comment by Nyun0** [comment]
Yes, this is the one I was tring to find any kind of information whether this behavior is correct or not. If you want I can dump my server world somewhere for anyone to test and see what it looks like.

**Comment by Speiger** [comment]
@Nyun0 @xJon The [Wiki Entry](https://github.com/TinyModularThings/IC2Classic/wiki/Wave-Generator) itself says:
It checks up to 50 blocks in one direction for water and the more water there is the better it produces.

It should be clear that the block isn't a "chunkloader" meaning if you go away from it and the "chunks unload" it sees less water blocks.
Simply chunkload the 2-3 chunks it checks extra and you should be fine.

**Comment by Nyun0** [comment]
@Speiger but if I am 10 blocks _above_ the generators, it should not (IMO) have any impact on the generators, as they are place at the surface level of the water, so no chunks are unloaded that could potentially deliver "less" energy, as there should not be less water blocks, am I correct?

**Comment by Speiger** [comment]
@Nyun0 
That can be easily explained too by this line:
```
Because of it cheap price it fluctuate in powerproduction increaseing/decreasing poweroutput everytime it refreshes.
```
every 256 ticks (12,8 seconds) the wave gen updates its power production.
The Water sources just define the "max", while there is a randomness factor included.
The randomness factor can move it between 10% or 110% of production.

So most likely you just ran in a low/high depending when you checked.

**Comment by Nyun0** [comment]
@Speiger I don't think that is the case - I'm able to reproduce the results every single time. When I check the MFSU while standing on the generators it easily fills it up. Now without closing the MFSU interface I hover 11 blocks upwards - and the productions drops **and stays low for as long as until I lower myself at least that 1 block**. Then it starts to generate the EU greatly again. I guess I could record the video and upload that to YT if you want, or I could give you backup of my server world fo you to see.

**Comment by Speiger** [comment]
@Nyun0 please provide a video.
Also please the EU Reader start a measurement then wait 5-10 seconds then measure again.
After that do your "fly bug" for the same amount of time (or longer if you want to) and then measure again.

The Measuring is basically the most accurate data you can use.

**Comment by Nyun0** [comment]
@Speiger here is the video link: https://youtu.be/nc5NrME8O1Q

If you still want to get the EU readings let me know - I'll record another one, but I think this one already shows very consistent fluctuation in regard to player's proximity to the generators.

**Comment by Speiger** [comment]
@xJon at this point.
I looked at the code and there is 0 things in my code that does that and i checked through this now a lot.

@Nyun0 I know this is a lot to ask from you.
but could you make a copy of the world and test it with just ic2c enabled?
Because this is not possible with ic2c alone. I looked through the entire code and there is NOTHING (checked 3 times at this point) that can cause that...

I am pretty sure someone from the addon devs fucked up...

**Comment by xJon** [comment]
> It is very easy to notice by looking at the MFSU place near the generator - when I am standing on it I see that the unit is filled with EU really fast, despite constant flow to the Mass Fabricator.

@Nyun0 Also, are you sure this is not caused by different placement of the MFSU with your network of energy cables? 
Can you try to reproduce this but with the cables not connected to anything else? You might have more energy going into other things (e.g. Mass Fabricator) when placing the MFSU higher.

**Comment by Speiger** [comment]
@Nyun0 could you stash away the watch of flowing time?
Because that could be the cause. Because that accellerates tileEntities and that could be the cause.

**Comment by Nyun0** [comment]
@Speiger why would it be a lot to ask? I'm the one who asked in the first place :D

Sure I will copy the world and disable all of the other add-ons. If I'll have problems doing that I'll let you know.

In the meantime you can take a look at the world here: https://drive.google.com/file/d/1THWgD9PxDXG7pGrSst6Ld4Y-AD57_48t/view?usp=share_link

**Comment by Speiger** [comment]
@Nyun0 if the watch of flowing time is enabled then this is the scenario.
if you are far away the Generators produce as normal.
But if you are close the Watch of flowing time actually picks up on the TileEntities and accelerates them.
And since wave gens can output more then 32EU/t but more like 512EU/t they just output more each tick because you have multiple ticks passing inside them while the energyNet (that does make power flow) isn't affected by it.

meaning they produce more or less depending of you are nearby them.
This is funnily enough the only generator that is really affected by this feature.
All other generators are not affected by it... At least in any meaningful way.

**Comment by Nyun0** [comment]
> @Nyun0 could you stash away the watch of flowing time? Because that could be the cause. Because that accellerates tileEntities and that could be the cause.

Now that you mentioned it, it makes a lot of sense - the clock affects the area near the player :) Once I have turned it off the energy production looks exactly the same no matter if I am 10+ blocks above or 40+.

So this is not a bug, it's a feature (of the Watch itself) ;)

Thank you for assisting me on this one!

**Comment by Speiger** [comment]
@Nyun0 Just so you know.
You almost gave me a heart attack with this bug report.

I ask you kindly Please don't repeat that xDDDDD

**Comment by Nyun0** [comment]
It was a question, not a bug report! ;) But yeah, I gotchu :D

(Who would have known that the Wave Generator acts differently than other generators :P)

**Comment by Speiger** [comment]
@Nyun0 small service message.
NEVER EVER go nearby a Steam Reactor with said watch.
This could cause the steam reactors to explode because the tanks do not have unlimited capacity and if you fill up the steam tank or drain the water tank the steam vents stop cooling.
The acceleration just hurts you then xD

**Comment by Nyun0** [comment]
@Speiger thank you for heads up! That's why I have this unpopular opinion - about the Solar Arrays being perhaps expensive, but safe (although unaffected by the stuff like said watch) ;) I'm powering everything I can with energy from the panels, stored in MFU's and MFSU's, and use Electrical Engine with stuff requiring RF (hence the bug report I've created not far ago, as the Electrical Engine connects with the wooden pipes - too bad that Railcraft is out of support).

**Comment by Speiger** [comment]
@Nyun0 ic2c has a direct RF generator. Flux generators. 

Also solar arrays are fine but expensive to the point where people complain the mod is to hard.
This is why the IV transformer in the HV solar panel to give a shock effect to let people think: maybe this is unreasonable to use. Let's look at different things.

**Comment by Speiger** [comment]
Can be closed @xJon (He just had a watch of flowing time in his inventory)
