### ISSUE TITLE
Adding Extra Mods on top of a Tekkit 2 Server

### ISSUE THREAD

**Issue by donutt762** [xJon/Tekkit-2#166]
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (Mystcraft, Tinkers' Construct, TreeCapitator)
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

I'm playing on Tekkit 2 and I've added Mystcraft on top of 4 other mods, 2 of which being support mods for 2 other mods. Whenever I add Mystcraft, which I want because I simply love the mod, it's great for resource issues and just sometimes fun adventures, the server gives me one of two issues, one being "Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:crafting_table (net.minecraft.item.crafting.ShapedRecipes@6eaf6ced) produces unregistered item minecraft:crafting_table (net.minecraft.item.ItemBlock@1aea759d)" and "Fatally Missing Registry Entries."
I have attempted everything from installing multiple different Mystcraft versions on the server, resetting the config files, downloading the server's config files, and downloading the mod versions from the server and verifying that everything is the same version on the client side as well as the server side, but nothing is working. I keep getting those two errors.

**Comment by xJon** [comment]
The first error you mentioned (`...produces unregistered item minecraft:crafting_table`) is usually caused by server file corruption. I'd recommend you to copy over your world to a new server folder and re-add the mods, then try again.

**Comment by donutt762** [comment]
Okay, thank you. I will try this out.+

**Comment by donutt762** [comment]
So I copied my mods over into a new server folder and installed a new Forge client for 1.12.2, but I'm still getting the first error.

**Comment by donutt762** [comment]
I fixed it. I needed to weed out the incorrect mod, and I got rid of the conflicts.

**Comment by donutt762** [comment]
I fixed it. I needed to weed out the incorrect mod, and I got rid of the conflicts.

**Comment by donutt762** [comment]
It ended up not working with some of my friends, the same exact issue I encountered happened to them. I have no idea what's going on anymore as I've tried everything from copying config files over, copying config file data over, copying the mods list from the server into my own mods list as well as my friends' mods lists, and changing the server .jar file to a newer, more recent one.

**Comment by xJon** [comment]
Did your friends also add the same exact extra mods to their client?

**Comment by donutt762** [comment]
Yes, they did. I gave them a zip file with all the same mods in there.

**Comment by donutt762** [comment]
Patcher crashes Tekkit 2 and doesn't work well with Mystcraft when isolated, I think it's fixed.

**Comment by xJon** [comment]
By the way out of curiousity, which other mods did you add other than Mystcraft?

**Comment by donutt762** [comment]
I added Tinkers' Construct, TreeCapitator, and their parent mods Mantle (For Tinkers) and bspkrscore (For TreeCapitator).
