### ISSUE TITLE
Bio Generator blows up every 

### ISSUE THREAD

**Issue by OneAndOnleh** [xJon/Tekkit-2#169]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: Optifine
- **Crash/latest log link (if applicable)**: Not applicable

Hey guys!
So I was playing around in creative in the Tekkit 2 modpack and trying to figure out how to make the [Bio Generator](https://ftbwiki.org/Bio_Generator) work. And any machine I hooked it up to, it made it explode. I used every transformer from LV to IV
and the same thing happened. Is this intentional or a bug? On the wiki it says it outputs 8EU/t or 16EU/t so I'm confused as to why
it blew up any device I hooked it up to? If anyone can try this in their own client that would be great!

**Comment by xJon** [comment]
Unfortunately this is a known Forestry bug (https://github.com/xJon/Tekkit-2/issues/66). The workaround is to use an Adjustable Transformer :)
