### ISSUE TITLE
Cannot craft computer on my Tekkit 2 server

### ISSUE THREAD

**Issue by jarvalarv** [xJon/Tekkit-2#172]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes - optifine
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

I simply cannot craft a computer. cctweaked is on but when the recipe is placed in the table nothing appears.

**Comment by xJon** [comment]
Does this happen in a specific server only or also in singleplayer?

**Comment by jarvalarv** [comment]
I just tested: it only happens in the server I made by downloading server files. In single player creative it works fine, cheat and crafting. In fact, all the cctweaked items cant be crafted eg. wired modem, monitor, networking cable, disk drive on my server.

**Comment by xJon** [comment]
Is your custom server running modded at all? You need to make sure to launch the server using the launch server script.

**Comment by jarvalarv** [comment]
Hi Jon now you mention it I think this is the issue. I'm on a Mac and was struggling to run the server using LaunchServer.sh (I tried chmod a+x ) so I created a strart.command file and I think I'm just running plain minecraft server.

#!/bin/bash
cd "$(dirname "$0")"
exec java -Xmx6G -Xms6G -jar minecraft_server.1.12.2.jar

Strange becuase when I load it it lists all the mods I have. Why wont my LaunchServer.sh run?

**Comment by xJon** [comment]
You need to target the Forge file rather than the vanilla Minecraft server file :)

**Comment by jarvalarv** [comment]
Thanks so much for your help Jon. I have tried this, and I think I am running the wrong version of Java. I am on a very new Mac and Java 17.0.6 seems to be defaulted, I cant seem to divert to Java 8. I will update you but I think this is me being a noob.

**Comment by xJon** [comment]
Yes, you do need to use Java 8 - you can change the `java` part of the script to target your location of Java 8!

**Comment by jarvalarv** [comment]
AH!!! Jon! I redirected it and the Mac folder Java 8 saves to is called 'Library/Internet Plug-Ins' with a space. It couldn't find it in terminal cos it was looking for "Library/Internet"... I renamed it to "InternetPlug-Ins" and boom we have some sort of lift-off!

**Comment by jarvalarv** [comment]
![Screenshot 2023-03-18 at 12 48 19 Large](https://user-images.githubusercontent.com/128194592/226107018-fa8f4f40-1f45-415c-b838-8c50030e9953.jpeg)

I am so happy. Thanks Jon.

**Comment by xJon** [comment]
Good job :)
