### ISSUE TITLE
LP Sneaky Upgrade causes crash

### ISSUE THREAD

**Issue by stevee-bee** [xJon/Tekkit-2#173]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/GicO9Hb

**Describe the issue**

Crash occurs when attempting to configure a Sneaky Upgrade with a Pipe Controller on a MK1 Chassis Pipe connected to the bottom of a Red Matter Furnace. I posted the issue [here](https://github.com/RS485/LogisticsPipes/issues/1686) and found out that this was fixed in version 0.10.4.34 of Logistics Pipes. (I see the current Tekkit 2 environment is using 0.10.4.33.)

**Comment by xJon** [comment]
Will update very soon :)

**Comment by xJon** [comment]
Fix is now included in update `1.2.0` of the modpack!
