### ISSUE TITLE
Infinite Iron glitch??

### ISSUE THREAD

**Issue by OperaticTruth** [xJon/Tekkit-2#174]
I’ve got an alchemical chest almost filled with iron with a hopper below going into a rotary macerator. The macerator is piped out into other alchemical chests. Originally I wanted to do just do almost a full chest of refined iron ingots but the whole alchemical chest of refined iron ingots filled up and my iron supply was untouched. Long story short, I have filled up 9 alchemical chests full of refined iron ingots and my iron supply hasn’t gone down by 1 iron. Think this is a glitch maybe less so than a bug? Wanted to bring this to your attention though!

**Comment by xJon** [comment]
Hey! Can I ask what version of the modpack you're playing with?

**Comment by OperaticTruth** [comment]
Hey xJon. I was playing on 1.1.3 from the technic launcher. I just saw the 1.2.0 dropped. I updated and will check it out!

**Comment by OperaticTruth** [comment]
![image](https://user-images.githubusercontent.com/79865872/228552647-490692fa-e226-4438-ba25-538f83878744.png) For reference. I updated to 1.2.0 and it is still doing it. This is the same amount of iron I have had in there since the beginning and it's made the 7 chests full of refined iron.

**Comment by xJon** [comment]
This should be resolved in `1.2.3`.
