### ISSUE TITLE
Gem Leggings causes falling to below bedrock in spectator mode

### ISSUE THREAD

**Issue by OperaticTruth** [xJon/Tekkit-2#175]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: not applicable

In both 1.1.3 and 1.2.0 if you are wearing Gem leggings (the gravity greaves) and you enter spectator mode as soon as you go through a wall you fall below bedrock at -1 or -2 and you cant get back up without tping out. This is resolved by taking off at least the gem leggings before going into spectator.

Hope this helps!

**Comment by xJon** [comment]
I suspect this might be caused due to some mod interaction. I don't have the time right now to test it, but if you want you can try to remove some mods and see if the issue goes away. I'll try to look into it more later :)

**Comment by xJon** [comment]
As the mod doesn't appear to be in active development I'll close this for now. Thanks nonetheless for the report!

**Comment by OperaticTruth** [comment]
No worries! Happy to help identify issues where I can.

**Comment by xJon** [comment]
Will be fixed in the next pack update :)

**Comment by xJon** [comment]
Should be resolved in `1.2.2`.
