### ISSUE TITLE
Unloadable Saves for Version 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by Ozone5009** [xJon/Tekkit-2#177]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: Yes Energy Converters https://www.curseforge.com/minecraft/mc-mods/energy-converters
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Version 1.2.0 and 1.2.1 of the Modpack, When i create a save after quiting out normally and restarting the modpack the save does not load and I get stuck on a screen after selecting the save and all it shows is 0%

**Comment by xJon** [comment]
Could you fetch your latest log from a session in which this happened and post it with https://mclo.gs/ ?
Should be under the `logs` folder within the modpack installation folder.

**Comment by Ozone5009** [comment]
https://mclo.gs/tflO49w

**Comment by xJon** [comment]
Strange, the log seems fine on world load. Is this reproducible for every new singleplayer world? You can't reenter any new world after restarting once?
Also, does this still occur if you revert versions to `1.2.0`?

**Comment by Ozone5009** [comment]
This occurs on all the saves i make. And this is on 1.2.0 and 1.2.1 this doesn't happen on 1.1.3

**Comment by Ozone5009** [comment]
Ok so i deleted and reinstalled Java. It opened on the first launch then the Second one got the same error. First Run https://mclo.gs/e4zo9bx  Second Run https://mclo.gs/c4bMzYh

**Comment by xJon** [comment]
That's really weird. So if you revert to `1.1.3` the issue goes away?

**Comment by Ozone5009** [comment]
This is correct. It could be an Issue with AMD drivers. I am on the most recent. or Java or something else with my computer but i do not get the issue on 1.1.3

**Comment by xJon** [comment]
* Can you experiment with removing some of the added/updated mods in between `1.1.3` and `1.2.0`? their names are all listed [here](https://github.com/TechnicPack/Technic/commit/c1ca3a03f0bc206882a68755e5f38342570225c1).
* Do you have access to a different computer to test this on?

**Comment by Ozone5009** [comment]
I have no idea what I did but now there is no issue. I have removed the Energy Converter mod so maybe that was the issue. But now it works

**Comment by xJon** [comment]
So glad it works! 🎉
