### ISSUE TITLE
Unable to craft Plasma Core

### ISSUE THREAD

**Issue by wesselmeijer** [xJon/Tekkit-2#179]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

Even with sufficient resources (16 advanced alloy, 8 magnet and 1 plasma cell), the crafting table will not craft a plasma core. Plasma core does not show up as a crafting result even when importing the recipe from the HEI menu

**Comment by xJon** [comment]
Strange, I cannot reproduce this.
![Gif](https://user-images.githubusercontent.com/8945347/231794143-07df984a-7d35-4921-b807-d25f8e78249e.gif)
Does it occur only on a specific world?

**Comment by wesselmeijer** [comment]
Seems restarting (a few times) has resolved the issue. Not sure what would cause it but consider it fixed!
