### ISSUE TITLE
[Feature request] Nicer looking FML loading animation

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/Tekkit-2#18]
I've made a version of the loading animation that has a small white gradient overlay placed to the left

Here's a video showing the difference:
Old
https://user-images.githubusercontent.com/48618519/187297104-f6534b44-b0b6-4c8d-9e19-369f4155cb27.mp4

New
https://user-images.githubusercontent.com/48618519/187297119-18113fc6-79f5-45f1-9877-561b16183422.mp4

If this does end up used, I don't want credit or anything, it's just something that has been bugging me since the pack came out
Here's the updated asset:
![tekkit2new](https://user-images.githubusercontent.com/48618519/187297254-9d612cac-7265-44f9-bb98-993c85ef8d87.gif)

**Comment by xJon** [comment]
Included in `1.0.1`, thank you :)
