### ISSUE TITLE
ProjectE's timeWatchTEBlacklist does not work, causing issues

### ISSUE THREAD

**Issue by marshallv124** [xJon/Tekkit-2#186]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  (yes)
- **Are you using Java 8, 64-bit?**:  (yes)
- **Did you add any additional mods**:  (no)
- **Crash/latest log link (if applicable)**:   (not applicable)
- I confirmed this happens in singleplayer and multiplayer version 1.2.1

**Describe the issue**

The Watch of Flowing Time has a mechanic where you can activate it on your hotbar to provide bonus ticks to the surrounding blocks to increase operation speed. I noticed that when I did this in the same area as the Auto Crafting Bench (and to a lesser extent the Electrotine Generator) from Project Red, if the ability was left on until the bench ran out of power, it becomes impossible to recharge it at the same placement in the world. I found that if you move it to another block it charges fine (given the ability is toggled off), but placing it back in the same spot causes it to not be able to charge.

I also found that when connecting the broken setup to a working one using low load power lines, the issue spreads to that generator and auto crafting bench as well.

**Comment by xJon** [comment]
Should be resolved in `1.2.2` thanks to @ACGaming :)

**Comment by xJon** [comment]
This should be resolved now in `1.2.3`.
