### ISSUE TITLE
Infinite Rotary Macerators

### ISSUE THREAD

**Issue by InsectByte** [xJon/Tekkit-2#190]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes (so is the server)
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

When crafting the Rotary Macerator, pressumably with resources for 2 of more, it allows for the infinite crafting of Rotary Macerators.
It happens when using the recipe with the Obsidian blades requiring 2 per slots in the crafting table.

Upon clicking an item in the crafting grid after crafting the item, the items return as if the item was not crafting, except you get to keep it.

I have added a video of the "dupe" in action.

https://github.com/xJon/Tekkit-2/assets/72791212/8955b72b-3e3b-483f-8cf1-333d796478df

**Comment by xJon** [comment]
Should be resolved in `1.2.2` :)
