### ISSUE TITLE
IC2 and Blockcraftery Frame minor crash issue

### ISSUE THREAD

**Issue by vzvzxv** [xJon/Tekkit-2#194]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: [link to log ](https://pastebin.com/khSger4s)

**Describe the issue**
Minor bug, mod compatibility issue.
Placing an IC2 block into a Blockcraftery frame does the following:
(For example, Machine Block into Reinforced Framed Block)
- Frame becomes invisible, all faces of other blocks being contacted become invisible ("x-ray" effect)
- A number of these IC2 framed blocks in one area will lag the game when other blocks are added to nearby frames, or when other blocks are broken/placed.
- Blocks are breakable in creative mode, but attempting to break them in survival mode **crashes the game.**
- Does not seem to crash multiplayer servers. ✓

**Comment by xJon** [comment]
As Blockcraftery is not currently in active development, I'll close this for now.
