### ISSUE TITLE
Suggestion to replace LoliASM with NormalASM

### ISSUE THREAD

**Issue by vzvzxv** [xJon/Tekkit-2#195]
[NormalASM](https://modrinth.com/mod/normalasm) is a simple rename of LoliASM. Distances the mod from creepy connotations from the original author and mod name with no other changes.
Some take a large enough issue with this, that for example Pastebin will automatically deny pastes of Tekkit 2 Crash Logs due to the inclusion of the aforementioned mod's name.
![image](https://github.com/xJon/Tekkit-2/assets/826049/9891e48f-2750-4620-afd8-f4d6e0c3dc1f)

**Comment by xJon** [comment]
NormalASM is currently not available with the latest changes from LoliASM. Beyond that, LoliASM plans a big version update which will include a rebrand. Thank you for the suggestion nevertheless!
