### ISSUE TITLE
Additional teleport Pipes in solo world but not in server world/survival

### ISSUE THREAD

**Issue by eGonzalez184** [xJon/Tekkit-2#196]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

Additional teleport Pipes in solo world but not in server world/survival I dont know if this is intended but if it is please let me know of a way to disable this as it hinders my servers functions and over complicates things.

**Comment by xJon** [comment]
By default, they are hidden, due to bugs. I'd recommend you to use Ender Chests / Tanks instead.
