### ISSUE TITLE
Can't craft or place modded items

### ISSUE THREAD

**Issue by solymosips** [xJon/Tekkit-2#197]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**:  not applicable

**Help needed**

For some reason if we play on a hosted server via the original server that is shown in the website, we can't craft the modded items, can't even add most of them, even if we can add in a few, we either can't place them or can't drop it on the floor for some reason.
Any idea what could cause the problem?

**Comment by xJon** [comment]
You probably started a vanilla server - can you make sure you start the server using the included launch script?
