### ISSUE TITLE
Glitched pants from railman npc

### ISSUE THREAD

**Issue by PLPLUGIN** [xJon/Tekkit-2#20]
When you lvl railman villager to max he offers you totally broken, overpowered, glitched pants, they have a lot of enchants, even duplicated ones. You take no dmg in them but also you can't take them off as they crash your game!
![image](https://user-images.githubusercontent.com/64206241/187314416-72718590-3052-4bff-a687-e94599fe4393.png)

**Comment by xJon** [comment]
That's... interesting, hah! Could you please repost this issue over Railcraft's repository?
https://github.com/Railcraft/Railcraft/issues

**Comment by xJon** [comment]
Don't accept pants from strangers, lesson learnt.

**Comment by xJon** [comment]
Is this still an issue in version `1.1.0`? (Railcraft was updated)

**Comment by djdubbs12** [comment]
> When you lvl railman villager to max he offers you totally broken, overpowered, glitched pants, they have a lot of enchants, even duplicated ones. You take no dmg in them but also you can't take them off as they crash your game! ![image](https://user-images.githubusercontent.com/64206241/187314416-72718590-3052-4bff-a687-e94599fe4393.png)

Same. Can't take my pants off!! ( 😂 )

**Comment by xJon** [comment]
@djdubbs12 What modpack version are you using?

**Comment by djdubbs12** [comment]
> @djdubbs12 What modpack version are you using?

@xJon 1.0.5

![image](https://user-images.githubusercontent.com/92045860/196533851-c8b08395-03be-4100-b4b6-2b2ef8a07676.png)

**Comment by xJon** [comment]
@djdubbs12 If you can test whether this bug is still present in `1.1.0`, it'd be useful.

**Comment by djdubbs12** [comment]
@xJon Sure! Give me just a few to back everything up and update.

**Comment by djdubbs12** [comment]
@xJon Can confirm, issue is still present. Can't remove pants and "alt + Click" crashes the game still.

**Comment by xJon** [comment]
Thank you for the update, that's unfortunate. As it was reported to the author and Railcraft is not currently in active development I'll close this for now.

**Comment by djdubbs12** [comment]
@xJon Is it possible to delete the item in an update then add it back in? Or maybe client side?

**Comment by xJon** [comment]
@djdubbs12 If you're stuck you can rollback your save to a backup :)

**Comment by djdubbs12** [comment]
@xJon Oh I've had these on for over a month of daily play, that's not an option 😂. They aren't hurting me so I have no issue with them on for right now.
