### ISSUE TITLE
Unsure of Vajra Charge Behavior

### ISSUE THREAD

**Issue by ajkalantari** [xJon/Tekkit-2#201]
Basic details:

Are you using a legitimate Minecraft account?: yes
Are you using Java 8, 64-bit?: yes
Did you add any additional mods: no
Crash/latest log link (if applicable): not applicable

Description/Interrogative 
Use of Vajra tool depletes armor (quantumsuit chest plate), is this a bug or actual functionality?

Thanks

**Comment by xJon** [comment]
The QuantumSuit Chest Plate acts as a "portable battery", charging the used tools, so this is normal behaviour and not limited to just the Vajra.

**Comment by ajkalantari** [comment]
resolved.
