### ISSUE TITLE
Cant craft stone macerator

### ISSUE THREAD

**Issue by blackeagles1989** [xJon/Tekkit-2#205]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**
I have transferred the server files for tekkit 2 to my server host via FTP. and i have confirmed the files are all present when connecting to the game and trying to craft a stone macerator i follow the recipe however the resulting macerator is not shown in the output of the crafting bench and so i cant progress, is there something maybe iv done wrong or missed in setting up the server. I'm not sure what information i can give you from my server/client to help but if there's something specific you need i am happy to provide it.

**Comment by xJon** [comment]
You might've started a vanilla server. You need to make sure the server is using the launch script, or targeting the `forge-1.12.2-14.23.5.2860.jar` file.
