### ISSUE TITLE
I want to change the controls and the game crashed, and I can't restart it.

### ISSUE THREAD

**Issue by csivoknaj** [xJon/Tekkit-2#207]
**Basic details**
- **Are you using a legitimate Minecraft account?**: / yes
- **Are you using Java 8, 64-bit?**: / yes
- **Did you add any additional mods**: no
-- **Crash/latest log link (if applicable)**: link to log : https://mclo.gs/4j1V2o3

**Help needed**

A clear description of what help is needed.

**Comment by ACGaming** [comment]
Galacticraft does some _interesting_ stuff with keybinds, delete your `options.txt` file.

**Comment by xJon** [comment]
Can you mention which controls did you change it to?
