### ISSUE TITLE
Cant mount any Animal

### ISSUE THREAD

**Issue by Luccplay** [xJon/Tekkit-2#209]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue** I cant mount a animal. As when i try to do this the animal wont move and wont jump with saddle and without.

A clear description of what the issue is.

**Comment by xJon** [comment]
I can't reproduce this issue, does it occur to you only on a specific server, or singleplayer world?
