### ISSUE TITLE
Flux cables do not input power into the Forestry Farm

### ISSUE THREAD

**Issue by luigil101** [xJon/Tekkit-2#21]
**Basic details**
- **Are you using a legitimate Minecraft account?** yes
- **Are you using Java 8, 64-bit?** yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
When attempting to use the Electric Flux Generator to power a Farm, the flux cables it demands are unable to input power into the Farm gearboxes
The generator does successfully power other machinery, only the Farm is unable to receive power
Normal kinesis pipes do function as intended and provide power to the Farm

**Comment by xJon** [comment]
Another workaround would be to place a converter (Flux Generator, Electrical Engine) right on the Farm Gearbox.
Strange issue though, thanks for the report.

**Comment by xJon** [comment]
This should be fixed in version `1.1.0` :)
