### ISSUE TITLE
Tekkit 2 : Treasure map crash and corrupt

### ISSUE THREAD

**Issue by JivedTurkey** [xJon/Tekkit-2#213]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log 

**Describe the issue**

I found what i think was a treasure map in the stronghold. Once i picked it up my game crashed. Upon attempting to back on the game refused to load and continued crashing before any terrain or inventory loaded.

**Comment by JivedTurkey** [comment]
> 

https://mclo.gs/O6BGGl4

**Comment by xJon** [comment]
Should be fixed in `1.2.2` thanks to @ACGaming :)
