### ISSUE TITLE
Crafting an MV-transformer crashed Tekkit 2

### ISSUE THREAD

**Issue by UsernameTaken346** [xJon/Tekkit-2#216]
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log: https://mclo.gs/cSxswq2

**Help needed**

Latest Java edition installed as detailed in Discord, same problem. Manually or using a auto crafting bench, crafting a MV-transformer crashes Tekkit 2 (v1.2.1)

**Comment by xJon** [comment]
I believe this is the same issue as https://github.com/xJon/Tekkit-2/issues/190, and it should be resolved in version `1.2.2` of the pack :)

**Comment by xJon** [comment]
@UsernameTaken346 See https://github.com/xJon/Tekkit-2/issues/109, you can use an alternative auto-crafting recipe (or the alternative, non-stacked recipe for MV-Transformers).
