### ISSUE TITLE
1.2.2 incompatible with SpongeForge

### ISSUE THREAD

**Issue by Pulz-TCP** [xJon/Tekkit-2#217]
**Basic details**
- **Are you using Java 8, 64-bit?**:  OpenJDK 64-Bit Server VM, version 1.8.0_312
- **Did you add any additional mods**: yes, server-side mods - will need to test and then list them.
- **Crash/latest log link (if applicable)**: No crash log, but appended to latest.log

https://mclo.gs/PoLy1K1

**Help needed**

Have only had time to have a brief skim after updating, but might be specific to SpongeForge. Log hints potential compatibility issue with Mixin Booter

spongeforge-1.12.2-2838-7.4.7

**Comment by xJon** [comment]
(Replied in Discord)
