### ISSUE TITLE
Compact Jetpack recipe mistake

### ISSUE THREAD

**Issue by fwhs2000** [xJon/Tekkit-2#218]
Basic details
- Using a legitimate Minecraft account?:  Yes
- Using Java 8, 64-bit?:  Yes
- Any additional mods?: No
- Crash/latest log link (if applicable):  Not applicable
- 1.2.2

Crafting the Compact Jetpack doesn't consume all the advanced circuits it only consumes the first ones in the 2 separated stacks.

**Comment by xJon** [comment]
What modpack version are you playing on?

**Comment by fwhs2000** [comment]
Sorry it was the Regular Compact jetpack

**Comment by xJon** [comment]
This is now resolved now in `1.2.3`.
