### ISSUE TITLE
Gravisuit Nuclear powered armor interactions inconsistant with other Nuclear powered items

### ISSUE THREAD

**Issue by fwhs2000** [xJon/Tekkit-2#219]
Basic details
- Are you using a legitimate Minecraft account?:  yes
- Are you using Java 8, 64-bit?:  yes
- Did you add any additional mods: no
- Crash/latest log link (if applicable):  not applicable

The Gravisuit Mod nuclear armors are accessed differently than all nuclear jetpacks and other mods nuclear armors
Most nuclear items accessed by right clicking and equipped by shift right clicking

**Comment by xJon** [comment]
Hey, can you forward this to the mod author? https://github.com/TinyModularThings/IC2Classic/issues

**Comment by fwhs2000** [comment]
The Gravisuit mod armors are accessed differently than all the other nuclear items. I should have noticed that is was one mod iwth a problem but I missed an item, the Nuclear Gravitation Chestplate.

**Comment by xJon** [comment]
I understand, you suggest to switch Gravisuit Classic's `Advanced Nuclear Nano Chestplate` & `Nuclear Gravitation Chestplate` items' inventory/equipping behaviour on right click, to be in line with the rest of the nuclear jetpacks (including Gravisuit Classic's own `Advanced Nuclear Jetpack`).

**Comment by xJon** [comment]
Will be included in the next update of the modpack!

**Comment by xJon** [comment]
Included in `1.2.4` thanks to @ACGaming's help :)
