### ISSUE TITLE
Laser and Assembly table not working

### ISSUE THREAD

**Issue by Cardl** [xJon/Tekkit-2#221]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**
When I power lasers  and I put items into the assembly table, but I can not craft anything. The assembly table does not take power from the lasers.

**Comment by xJon** [comment]
Are you reporting this as a new issue of the new version? If not, do you have the correct spacing/setup between the lasers and assembly table?
