### ISSUE TITLE
I can't loader MFSU cart with EU loader

### ISSUE THREAD

**Issue by Willian-Massao** [xJon/Tekkit-2#226]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

MFSU cart can't loader using EU loader

**Comment by xJon** [comment]
Did you mean to close the issue?

**Comment by Willian-Massao** [comment]
Yes, sorry, I researched later and discovered that I had to install a
transformer upgrade

Em dom., 24 de set. de 2023 14:02, Jon ***@***.***> escreveu:
