### ISSUE TITLE
Some achievements are unlocking, some aren't...

### ISSUE THREAD

**Issue by Gridders** [xJon/Tekkit-2#227]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / yes
- YES
- **Are you using Java 8, 64-bit?**: no / yes
- YES
- **Did you add any additional mods**: yes (detail) / no
- YES - Twilight Forest
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

Some of the achievements are processing within the game, however, other's aren't.

**Comment by xJon** [comment]
Hi, which advancement are not working properly?

**Comment by Gridders** [comment]
Hi Jon, ignore me, I managed to play around and find out it was an issue with cheats enabled that wouldn't turn off. So that is my fault, but thank you for responding!
