### ISSUE TITLE
Watch of Flowing Time on a Pedestal crash

### ISSUE THREAD

**Issue by Iccariam** [xJon/Tekkit-2#229]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/ipopGjJ

**Help needed**
The game suddenly crashes and then I can't reload the world. it only gives me the HUD and the minimap everything else is black then the window pops up saying "app is no longer responding". I tried to wait but nothing happens. It happened twice and there was nothing special. I had just started joining recently.

PC : MSI
GC: gfoce gxt 1050ti
pro: i7 777 7th
8gb ram

all drivers are dowloaded

**Comment by xJon** [comment]
This is a known bug in the current version and will be fixed in the next modpack update :)

**Comment by xJon** [comment]
For now one can manually update to the latest build of ProjectE to workaround this issue, over https://github.com/ACGaming/ProjectE/actions.

**Comment by ACGaming** [comment]
As action build artifacts are expired by now, I have released the current version: https://github.com/ACGaming/ProjectE/releases/tag/PE1.4.6

**Comment by xJon** [comment]
This is now resolved in `1.2.3` :)
