### ISSUE TITLE
IC2 Bronze wrench having crash issues with everything.

### ISSUE THREAD

**Issue by LividDarkness** [xJon/Tekkit-2#23]
Basic IC2 bronze wrench will only pick up the machine or item via wrenching from the exact front face of the block. Any other side or angle causes a crash. Making machine adjusting or removal a pain in the rear.

For reference is the crash log for the mod creators perusal: https://mclo.gs/JesbLza

Hope this helps for fixing the issue.

**Comment by xJon** [comment]
Hey, thanks for the report! You can see more info over https://github.com/xJon/Tekkit-2/issues/12, I hope this get fixed soon.
