### ISSUE TITLE
AE2 doesn't work with the Tekkit2Content Mod

### ISSUE THREAD

**Issue by FrozenGhostx** [xJon/Tekkit-2#230]
**Basic details**
- **Are you using a legitimate Minecraft account?**: no / **yes**
- **Are you using Java 8, 64-bit?**: no / **yes**
- **Did you add any additional mods**: **yes (AE2)** (detail) / no
- **Crash/latest log link (if applicable)**: link to log / **not applicable**

**Describe the issue**

Dedicated Server won't start if AE2 is implemented

A clear description of what the issue is.

BlockFluxCable overrides a minecraft method public void addInformation(ItemStack stack, @Nullable World world, List<String> tooltip, ITooltipFlag flags)
The method uses interface ITooltipFlag which is a client-side only class and is NOT available on dedicated servers, thus it causes crashing.
The solution is: inspect minecraft source code and see that addInformation has @SideOnly(Side.CLIENT) annotation, which MUST be included in all overrides of said method.

**Comment by xJon** [comment]
Have you considered removing the Tekkit mod? It adds Jaffa Cakes and RF cables, but if you're modifying the pack you could add alternative RF cables as well.

**Comment by FrozenGhostx** [comment]
I did, but that's just a workaround and no final solution. This problem only occurs on server-side, on client-side the combination of this mods works.

**Comment by xJon** [comment]
Currently I don't have another solution, and the flux cables are using [Cable Flux](https://www.curseforge.com/minecraft/mc-mods/cable-flux) as a library mod - it is open source if you want to have a look at it.
As AE2 is not included in the modpack by default I don't see it as a bug, but I'm sorry about the inconvenience.

**Comment by xJon** [comment]
As I'm unable to resolve it myself, and AE2 is not included in the modpack by default, I'll close this - but again I'm sorry about the inconvenience. If you are able to patch it yourself I'll look into including this by default in the pack.
