### ISSUE TITLE
unable to use destruction catalyst on server

### ISSUE THREAD

**Issue by coolian1337** [xJon/Tekkit-2#231]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
On my server i cant use the destruction catalyst however in singleplayer i can.
we use tekkit 2 version 1.2.2

**Comment by xJon** [comment]
I'm currently unable to verify this issue myself, but it appears it also affects a public Tekkit 2 server, so I'll mark this as a minor bug until I can look into it further.

**Comment by xJon** [comment]
I've tested this on a plain server using the latest modpack version and I'm unable to reproduce the issue. Have you modified the server in any way?

**Comment by coolian1337** [comment]
The server was originally tekkit version 1.2.1 which i then updated by copying the mods, scripts, config, and asm directories to the server from the serverpack download that is available on the technic website.

**Comment by xJon** [comment]
Can you reproduce the issue if you setup a new server?
Are you set as OP on the server?

**Comment by coolian1337** [comment]
Unfortunately the way i even got a server in the version 1.2.1 is by renting a server on nitrado which means i would need to pay more money to get another instance of a 1.2.1 server because i dont think i can download an older version of technic

**Comment by xJon** [comment]
Is there a reason you're not running the latest version of the modpack (`1.2.2`)?

**Comment by coolian1337** [comment]
I am using the latest version but nitrado doesnt have the latest version so i had to update that myself

**Comment by coolian1337** [comment]
no i dont really need the destruction catalyst anymore anyways as im in the endgame and akliz is more expensive.
if you want i can close this issue even if it wasnt resolved as i dont need the destruction catalyst anymore

**Comment by xJon** [comment]
No worries, and nevertheless I appreciate the bug report.
