### ISSUE TITLE
Glass fiber cables break when i go away from base.

### ISSUE THREAD

**Issue by MrTordse** [xJon/Tekkit-2#233]
**Basic details**
- I am using legit minecraft account
- I am using java 8 64bit
- i did not add any additional mods

Every single one of my glass fibre cable blocks disconnect from each other when i go away from my base area to explore the world. I need to exit the server and load back to the server for the cables to return to normal.

**Comment by xJon** [comment]
@Speiger I believe it's a known bug that's not expected to be resolved in 1.12.2?

**Comment by Speiger** [comment]
I know you have been waiting a long time for a patch that i promised.
(I haven't forgotten it, still busy on my mega project)

I think this is a thing i can fix without making a game breaking patch that isn't compatible with others.
I won't promise that it will be fixed but I will try looking into it.
please open a issue inside the ic2c issue tracker for it ^^"

Also sorry that i kept you waiting for so long.

**Comment by xJon** [comment]
I have opened https://github.com/TinyModularThings/IC2Classic/issues/916, thank you for looking into it Speiger!

**Comment by xJon** [comment]
This should be resolved now in `1.2.3`.
