### ISSUE TITLE
Cannot login to ReAuth, despite being logged-in in Technic Launcher

### ISSUE THREAD

**Issue by Nyun0** [xJon/Tekkit-2#236]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:*yes ('_Use Mojang Java runtimes_' checked in the launcher options)
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Help needed**

@xJon, could you point me in the right direction as to what can I check to make my wife's account be visible by ReAuth as online in _Tekkit 2_? She is authenticated in the _Technic Launcher_, we performed a clean installation of _Tekkit 2_ (v1.2.2 but the same issue was with 1.1.3) and upon loading the main screen and going into _Multiplayer_, at the top we can see that ReAuth status shows red cross instead of green checkmark.

Now it might be important that her account is **not** migrated from Mojang to Microsoft.

I was trying to search around google about the possible issues, but sadly I gave up as I couldn't find anything about such occurance. Since I am hosting a server in our LAN, I've simply changed the config to allow offline account and through ReAuth we simply setup her a nickname so the server remembers her client's player parameters and stuff, but since I've upgraded the server from 1.1.3 to 1.2.2 today this started to bother me again - what if she wanted to join some server outside of our home realm?

Any help would be much appreciated ;)

**Comment by aclemens185** [comment]
I am experiencing the same error with the same details.

**Comment by xJon** [comment]
> Now it might be important that her account is **not** migrated from Mojang to Microsoft.

That is the reason, unfortunately. Since somewhat recently Microsoft stopped supporting Mojang accounts on multiplayer.

**Comment by aclemens185** [comment]
@Nyun0 

I did the following and was able to get back into my account on Technic: 

1. Made sure the Microsoft Minecraft account had a username.
2. Ran the Java version of Minecraft from the Microsoft store.
3. Signed in to the Technic launcher using the Microsoft account option.

Thank you, @xJon, for chipping in. Your comment gave me the idea to start looking into my Microsoft account.

**Comment by Nyun0** [comment]
@xJon 
> > Now it might be important that her account is **not** migrated from Mojang to Microsoft.
> 
> That is the reason, unfortunately. Since somewhat recently Microsoft stopped supporting Mojang accounts on multiplayer.

To be frank, when she is launching the vanilla version using _Technic Launcher_ she is pretty much online. That is actually the reason why I asked (don't shout at me, just thought this has something to do with the mod itself rather than the fact that MSFT is not supporting Mojang accounts).

@aclemens185 
> @Nyun0
> 
> I did the following and was able to get back into my account on Technic:
> 
>     1. Made sure the Microsoft Minecraft account had a username.
>     2. Ran the Java version of Minecraft from the Microsoft store.
>     3. Signed in to the Technic launcher using the Microsoft account option.

Well my account **is** migrated and I never had problem with being online in either _Technic Launcher_ or the _Tekkit 2_ itself. My wife's account however is online only in the launcher, but not upon starting the modpack.

Again - she is online when launching the vanilla MC. Just not when launching the _Tekkit 2_.
