### ISSUE TITLE
cant see eu prodution when hovering over the symbols

### ISSUE THREAD

**Issue by SLmannen** [xJon/Tekkit-2#243]
I am using a legitimate version and the latest 64 java version whichever that is. The problem is as stated in the title. When i hover over, for example my generators battery amount with my pointer it doesn't show exactly how much EU is in it. I have played some other version of tekkit on curseforge called something like tekkit classic and it works as it should there. Can i please get some help? i also have not installed any additional mods to the modpack, just the default tekkit 2 modpack on techniclauncher. Thanks.

**Comment by xJon** [comment]
You need to use the EU Reader - https://github.com/TinyModularThings/IC2Classic/wiki/EU-Reader
