### ISSUE TITLE
Changing sneak keybinding crashes game

### ISSUE THREAD

**Issue by SirPhoeniix** [xJon/Tekkit-2#244]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: 1.8.0_51 64-bit
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/JKyKJpb

**Describe the issue**

Game crashes after changing the sneak key to `<` (QWERTZ keyboard layout).
Main menu is also crashing. Had to delete the options.txt file and restart the game.

Afterward, my keybindings were reset, and I was able to start the game again.

**Comment by xJon** [comment]
Can you post this issue to https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues for further tracking?

**Comment by SirPhoeniix** [comment]
Hi,
yes I have created an issue here: https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/181

**Comment by xJon** [comment]
This should be resolved now in `1.2.3`.
