### ISSUE TITLE
I can not craft modded items, modded ores do not seem to show up 

### ISSUE THREAD

**Issue by Assassin-reese** [xJon/Tekkit-2#249]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

I started a server for myself and freinds to play on. While making sure everything is working I noticed that none of the modded items are able to be crafted and I couldn't find any of the modded ores while mining. I am using what I believe to be the correct jar file to run the server. It says forge-1.12.2-14.23.5.2860.jar in my files for the server

**Comment by xJon** [comment]
You need to launch the server through the `LaunchServer` file.

**Comment by Assassin-reese** [comment]
I have been using the launchserver.bat file in order to do so. Is that correct?

**Comment by xJon** [comment]
Yes.

**Comment by xJon** [comment]
There's no specific support for Hamachi, I'm not sure what issues its usage can create.

**Comment by ACGaming** [comment]
> C:\Users\massa\OneDrive

Please do not run a Minecraft server in a OneDrive folder, the constant syncs lock various files and can corrupt your server instance in the process.

**Comment by xJon** [comment]
Closed due to inactivity.
