### ISSUE TITLE
Rending Gale not protecting tilled land

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/Tekkit-2#25]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (Corail Tombstone)
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Swiftwolf's Rending Gale does not protect from trampling on crops, as shown in this video:
https://streamable.com/pnywbp
This is a documented behaviour of this item on the Tekkit Classic wiki: https://tekkitclassic.fandom.com/wiki/Swiftwolf%27s_Rending_Gale

**Comment by xJon** [comment]
It doesn't appear to be a configurable option of ProjectE, so I'm just left to assume they didn't implement this feature. Unfortunately the mod is no longer developed for 1.12 so there's not much we can do unless the author changes their mind

**Comment by ACGaming** [comment]
Should I implement that in my fork?

**Comment by xJon** [comment]
@ACGaming Would be awesome :)

**Comment by OpenSauce04** [comment]
Oh wait that was a Project E thing? Cool, glad to see that implemented :)

**Comment by xJon** [comment]
@OpenSauce04 Apparently it was a feature that was broken in ProjectE 1.12.2. @ACGaming fixed it so it will be in the next modpack update :)

**Comment by xJon** [comment]
Included in `1.0.1` :)
