### ISSUE TITLE
I Have problem with start Tekkit 2 Modpack after Update

### ISSUE THREAD

**Issue by PepanC** [xJon/Tekkit-2#251]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/ZGDV20d

### Please describe the issue you are experiencing

When I run the modpack, when loading it says an error saying it can't be run.

![log](https://github.com/xJon/Tekkit-2/assets/168340665/c7e26a4c-fe7c-4f09-aa93-a3b3ad51576a)

**Comment by xJon** [comment]
Could you try to go to the modpack's installation folder and delete the `crafttweaker.log` file?

**Comment by PepanC** [comment]
Yes, now it´s works, thank you.
