### ISSUE TITLE
Tekkit 2 wont download thru Technic Launcher

### ISSUE THREAD

**Issue by ussdylan** [xJon/Tekkit-2#252]
### Was this help requested before?

- [X] No, it was not.

### Please describe what you need help with

Hey! When downloading the tekkit 2 modpack, i get an error message (see attached) giving me a 500 error code whenever trying to download the Forge .jar (i assume?), went into the Technic discord and asked for help but they said it was likely a server side issue so here i am!

Just reporting here incase ur unaware OR know how to fix this! Thanks a ton for the help AND the modpack
below is error popup after getting to abt 60-70% into the download process 

![image](https://github.com/xJon/Tekkit-2/assets/147904905/30c63b56-d705-4ea0-a9a8-0602a8381717)

**Comment by xJon** [comment]
Hey! Is it still an issue?

**Comment by xJon** [comment]
Closed due to inactivity.
