### ISSUE TITLE
Server Assistance

### ISSUE THREAD

**Issue by TheChubbiNerdAtDuck** [xJon/Tekkit-2#253]
### Was this help requested before?

- [X] No, it was not.

### Please describe what you need help with

Hi, so Im trying to run a local run server  for 1.12.2 modded minecraft (tekkit 2) and Ive been researching ways to make plugins work with it, but was wondering if anybody could help me out here, Ive tried runing craftbukkit but it doesnt load the modded items and crashed when i run into an item that isnt loaded serversided but is client sided and proceeded to crash the server and will keep crashing due to being in a block not loaded by the serverside with craftbukkit, is there a way to enable plugins with forge? Was going to try and use magma but it doesnt work, cant figure out what to do without the original jar file. returning dev looking for help.

**Comment by xJon** [comment]
You can try to simply use https://www.curseforge.com/minecraft/mc-mods/forge-essentials as a mod, but for full plugin support there is https://github.com/Luohuayu/CatServer/blob/1.12.2/docs/README_EN.md.

**Comment by TheChubbiNerdAtDuck** [comment]
Ive tried CatServer is too unstable I cant even break trees yo.

**Comment by xJon** [comment]
@TheChubbiNerdAtDuck CatServer shouldn't case that, it might be setup incorrectly. You can join their Discord server for support.

**Comment by TheChubbiNerdAtDuck** [comment]
define setup incorrectly I literally followed the install instructions. Forge Essentials Seems like a good compromise, but I really prefer to use real server jars, so this is the script Im using its the default script for tekkit 2 servers
"@ECHO OFF

:: When setting the memory below make sure to include the amount of ram letter. M = MB, G = GB. Don't use 5GB for example, it's 5G ::

:: This is allocated memory ::
set mem=3G

:: Don't edit past this point ::
ECHO [Tekkit 2] woah guys Im thinking...
ECHO [Tekkit 2] Java 8? whats that?

java -server -Xmx%mem% -XX:+UseG1GC -Xms2G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.queryResult=confirm -Duser.language=en -jar CatServer.jar gui

PAUSE
"

**Comment by xJon** [comment]
I apologise but I am unable to provide full support for plugins. Personally I recommend either ForgeEssentials or CatServer.
