### ISSUE TITLE
Nickel ore not generated in Overworld but can be mined in Overworld with an Industrial Foregoing Laser Drill.

### ISSUE THREAD

**Issue by LouVanSoom** [xJon/Tekkit-2#255]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Industrial Foregoing Laser Drill configuration file still has Nickel set to be able to be mined in the Overworld while there is no Nickel generation in the Overworld.

**Comment by xJon** [comment]
That is intentional, it is configured to be generated by default only in the Nether.

**Comment by LouVanSoom** [comment]
Yes but then why can the Laser Drill find Nickel in the Overworld? Don't you find that inconsistent?

**Comment by xJon** [comment]
That's a good point - I'll look into making the laser ores more consistent with the Overworld/Nether.

**Comment by xJon** [comment]
This is improved in `1.2.4` :)
