### ISSUE TITLE
Nuclear Gravitation Chestplate plays a constant equip sound when equipped

### ISSUE THREAD

**Issue by Cay1987** [xJon/Tekkit-2#257]
### Was this bug reported before?

- [X] No, it was not.

### If you have any, please provide a list of additional mods

Gravisuit Classic

### Please describe the issue you are experiencing

Nuclear Gravitation Chestplate plays a constant equipping sound for you and players around you when equipped.

To repeat this bug all you have to do is equip the chestplate and it's spamming in your headphones until you take it off. Have to mute player sounds to stop it while wearing it. Now this is only on a server, I tried to duplicate this on singleplayer but it didn't duplicate. Server creator said to report so here I am.

**Comment by xJon** [comment]
Can you reproduce it in a new world? I'm unable to.
Can you please also test whether manually updating to [`gravisuit-1.0.8.9.jar`](https://github.com/ACGaming/Gravisuit-Classic-Edition/releases/tag/1.0.8.9) resolves the issue?

**Comment by Cay1987** [comment]
> Can you reproduce it in a new world? I'm unable to. Can you please also test whether manually updating to [`gravisuit-1.0.8.9.jar`](https://github.com/ACGaming/Gravisuit-Classic-Edition/releases/tag/1.0.8.9) resolves the issue?

I created a new single player world and it did not duplicate either. I'll see about the server creator updating the gravisuit mod, will update when its done, most likely today.

**Comment by Cay1987** [comment]
> Can you reproduce it in a new world? I'm unable to. Can you please also test whether manually updating to [`gravisuit-1.0.8.9.jar`](https://github.com/ACGaming/Gravisuit-Classic-Edition/releases/tag/1.0.8.9) resolves the issue?

I have made a server myself and there doesn't seem to be an issue, maybe it's a server issue? I honestly have no clue since the issue can't be duplicated for the server I made and the singleplayer world.

**Comment by xJon** [comment]
Strange, perhaps the issue can be further investigated by the server owner, if they made any changes to their server?

**Comment by Cay1987** [comment]
> Strange, perhaps the issue can be further investigated by the server owner, if they made any changes to their server?

I got a reply, admins were able to replicate it on the server, I don't know these terms as I'm not a server guy so.
He3 said he replicated it on a catserver. He said they are attempting to fix. I'll keep you updated on it if that's the case.

**Comment by Cay1987** [comment]
I assume this has been deemed a catserver issue:

Movements for resolution: Catserver report made, hopefully they fix it.

**Comment by xJon** [comment]
If they want, they can feel free to publish a pull request over https://github.com/ACGaming/Gravisuit-Classic-Edition.
