### ISSUE TITLE
Galacticraft sealed IC2 cables won't work

### ISSUE THREAD

**Issue by Ramog** [xJon/Tekkit-2#258]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

In Tekkit 2 - v. 1.2.3 sealed IC2 cables (Copper cable, Gold Cable, Glass Fiber Cable, HV Cable, Tin Cable) won't conduct EU (maybe a problem that is caused by an incompatibility of IC2 classic to IC2?). Other sealable blocks seem to work as they should.

Another user has told me that it worked in Tekkit 2 - v. 1.1.3 althought I couldn't test that out.

**Comment by xJon** [comment]
This is fixed in `1.2.4`.
