### ISSUE TITLE
Wireless misaligned

### ISSUE THREAD

**Issue by enginme** [xJon/Tekkit-2#261]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

**Important note: I am not a native speaker, and that's my first time here so please let me know if there are any misunderstandings.**

I would like to report a bug. When I move away from the base, the transmitter and receiver become "misaligned"; in other words, the transmitter appears to be on while the receiver appears to be off. This is an issue on several occasions, such as when I turn the nuclear reactor alarm system on or off, or the defense system with the Tesla coils. I am now trying with a "world anchor," but this is still an unexpected behavior.

**Comment by xJon** [comment]
Are you playing on a specific server?
Are you able to reproduce the issue in a test singleplayer world?

**Comment by enginme** [comment]
> Are you playing on a specific server? Are you able to reproduce the issue in a test singleplayer world?

Yeah sure, it's the Tekkit 2 v1.2.3

**Comment by xJon** [comment]
I meant to ask:
1. In what server/world are you experiencing this issue?
2. Can you create a new creative singleplayer world, and experience the issue in it? Or is it limited to your existing world?

**Comment by enginme** [comment]
> I meant to ask:
> 
> 1. In what server/world are you experiencing this issue?
> 2. Can you create a new creative singleplayer world, and experience the issue in it? Or is it limited to your existing world?

1. In my private server.
2. Sure, i can try

**Comment by enginme** [comment]
I can confirm

**Comment by xJon** [comment]
Even with a World Anchor running? Can you explain your setup so I can try to reproduce the issue myself?

**Comment by enginme** [comment]
> Even with a World Anchor running? Can you explain your setup so I can try to reproduce the issue myself?

Sorry for the late answer.
I use the wireless transmitter to send a signal to the wireless receiver using a lever. But even if I "turn on" the signal by lowering the lever and then leave, when I return, the receiver will be "off" but the transmitter will still be on. To realign the signal, I will have to break the receiver and place it again. (Turning the signal off and on again using the lever won't work, as if the receiver were on a different frequency.)

**Comment by enginme** [comment]
When i return i will try with a World Anchor (maybe i can ask to a friend)

**Comment by xJon** [comment]
Closing as it was resolved by using a chunk loader 👍
