### ISSUE TITLE
Import mod not working

### ISSUE THREAD

**Issue by Rpgates2000** [xJon/Tekkit-2#263]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

I am trying to use import upgrades to pull items from an alchemical chest above into the compressor, recycler and the induction furnace with no luck. It is working for the macerator and extractor using the exact same set up.
![image](https://github.com/user-attachments/assets/4654ffb0-7f00-40d6-a89a-5e2a20771c37)
I have tried using different chest and the basic upgrade version however cannot get it working.

**Comment by xJon** [comment]
Hi, I tried using an Importer Upgrade on both a normal and a Singularity compressor, and I'm unable to reproduce this.
Perhaps the upgrade is being used incorrectly? You can read more about it over https://github.com/TinyModularThings/IC2Classic/wiki/Machine-Upgrades#import-upgrade.
