### ISSUE TITLE
Logistics Pipes IC2 Power Supplier Upgrade not working

### ISSUE THREAD

**Issue by Ramog** [xJon/Tekkit-2#269]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

If you setup an `EU Power Provider` and create a working [power network for your LP-System](https://ftb.fandom.com/wiki/Getting_Started_(Logistics_Pipes)#Transporting_Power) it will not work unless you leave the world and load it again.
**But even then** only the laser beam in the pipes shows up, no power is put into the machine that the `IC2 Power Supplier Upgrade` is attached to.
I was told that this is unique to EU, the RF part of this system seems to work without problem.

https://github.com/RS485/LogisticsPipes/issues/1712

**Comment by xJon** [comment]
Thank you for the report - closing due to https://github.com/RS485/LogisticsPipes/issues/1712#issuecomment-2501067202.
