### ISSUE TITLE
Project table crashes world and deletes it's items at random

### ISSUE THREAD

**Issue by dangerdyke** [xJon/Tekkit-2#29]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: [link to log](https://mclo.gs/Q9vwKu6)

**Describe the issue**

Sometimes while crafting using a project table, the game will crash. upon re-entering the world, one of the stacks in the project table's inventory will be dropped on the ground, while everything else will simply be gone. There is no discernable pattern to when this occurs.

**Comment by xJon** [comment]
Do you have a way to reproduce this?
Can you try to head to the modpack's installation folder -> `config` -> `placebo.cfg`, disable `"Fast Shapeless Recipes"` and try again?

**Comment by dangerdyke** [comment]
after trying on and off for a few hours i couldn't reproduce with that config change

**Comment by xJon** [comment]
@dangerdyke and you can reproduce it again without the config change? (`Fast Shapeless Recipes` enabled)

**Comment by dangerdyke** [comment]
Yes, the issue does come back with the option re-enabled

**Comment by xJon** [comment]
Will make sure it is disabled by default in the next modpack update. Thanks for the report!

**Comment by xJon** [comment]
Should be fixed in `1.0.1`.
