### ISSUE TITLE
logistics pipes autocrafter needing more than 1 programmer

### ISSUE THREAD

**Issue by TotallyNotAGhost** [xJon/Tekkit-2#34]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Logistics pipes autocrafters want 1 progammer and an additional 1 for each logistics pipe item they're crafting even if it's not consumed in the crafting.
![2022-09-01_20 59 07](https://user-images.githubusercontent.com/112681977/188067156-babee340-5046-423e-9166-1e5f5bdee314.png)
![2022-09-01_20 59 11](https://user-images.githubusercontent.com/112681977/188067161-b0232d50-fe20-46d1-8e92-18653288f887.png)
![2022-09-01_20 59 33](https://user-images.githubusercontent.com/112681977/188067166-f0f1c843-96ea-43ad-a644-fd810d058e1a.png)
![2022-09-01_20 59 35](https://user-images.githubusercontent.com/112681977/188067167-50a69ddd-4d58-48b5-941d-07b89f40ac60.png)

**Comment by TotallyNotAGhost** [comment]
The solution to this (thanks to Kriest on discord) is to remove the programmer from the crafting pipe input and leave everything else.

**Comment by xJon** [comment]
If you think this design choice is unintuitive, feel free to open an issue discussing it over the mod's repository! https://github.com/RS485/LogisticsPipes/issues
