### ISSUE TITLE
Logistics autocrafter doesn't correctly distribute items

### ISSUE THREAD

**Issue by TotallyNotAGhost** [xJon/Tekkit-2#35]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: y no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Logistics autocrafter doesn't correctly distribute items among it's slots sometimes, resulting in stuck autocrafting.

![2022-09-02_02 22 19](https://user-images.githubusercontent.com/112681977/188121169-813801eb-389d-437f-8784-d655a5820818.png)

**Comment by Jaari** [comment]
The only thing I see there is that you are missing the block in the middle? It's not in the inventory.

**Comment by xJon** [comment]
Can you explain in further detail?
Also, it might be better to consolidate all Logistics Pipes issues to one reported to the modpack, or post them directly over https://github.com/RS485/LogisticsPipes/issues. The mod is not currently in active development but could be later by other maintainers so keeping track of issues is a good thing.

**Comment by TotallyNotAGhost** [comment]
You're right, it's missing the center block, I went and looked at the previous fuzzy crafting table, and the recipe in it wants oak planks and refuses to use the jungle planks that were given to it by the system. I'm just closing this because I think I messed it up and wasted your time, sorry.

**Comment by xJon** [comment]
@TotallyNotAGhost You didn't waste our time, it's valuable to report issues. Thank you nonetheless :)
