### ISSUE TITLE
CCL Error rendering Logistics Crafting Table

### ISSUE THREAD

**Issue by MCDemon117** [xJon/Tekkit-2#36]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: Yes (Telepads Mod)
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

This error appeared before I added the Telepads Mod, it started after I returned from the Moon the first time, I looked into the log myself and I believe the source of the problem is the Logistics Pipes Crafting Table.

(Please use a paste tool) https://mclo.gs/Hw824jj

**Comment by xJon** [comment]
Are you using any Project Red frames?

**Comment by MCDemon117** [comment]
No and I don't have Optifine since I know it causes a small problem, I'm telling the truth, it's something to do with Logistic Pipes Crafting Table

**Comment by xJon** [comment]
Forwarded the issue to Logistics Pipes' repository in case development is picked up again, although I'm not sure when that would be. Thanks nonetheless for the report!

**Comment by xJon** [comment]
Should be fixed in `1.0.3` thanks to @bziemons :)
