### ISSUE TITLE
Tree Fluid Extractor not Working With Rubber Wood

### ISSUE THREAD

**Issue by Fireflexor** [xJon/Tekkit-2#38]
The IF tree fluid extractor does not appear to work with IC2 Classic's rubber trees. in the source code it appears to check if the log is "ic2:rubber_wood" however in IC2 Classic it is called "ic2:blockrubwood". This means that instead of producing 4mb of latex per operation (more than any of the vanilla trees) it produces none. This can be fixed using craft tweaker

**Comment by xJon** [comment]
Fixed in `1.0.1`, thank you for the report :)
