### ISSUE TITLE
Musket and Blunder not working

### ISSUE THREAD

**Issue by Darklus1** [xJon/Tekkit-2#4]
whenever we try loading the gun to shoot makes a ringing noise and does not shoot, the guns show it stuck in loadstate reloading.

Kind regards

**Comment by xJon** [comment]
Found out what causes this, will fix soon :)

**Comment by Darklus1** [comment]
Many thanks, Just FYI same issue with Crossbows, ^^ Just FYI love it ^^

**Comment by Darklus1** [comment]
Hello, 

Just curious when this will be fixed? 

Kind regards

**Comment by xJon** [comment]
Hopefully this weekend :)

**Comment by ThexXTURBOXx** [comment]
Joining in here, I have received a huge PR on Reforged which should hopefully fix this.
I will review it in the next few hours and see whether everything works then. Depending on that, I will publish a new version of Reforged then.

**Comment by xJon** [comment]
Fixed in `1.0.1` thanks to @ThexXTURBOXx & @phantamanta44 :)
