### ISSUE TITLE
ProjectE projectile fire default key binding conflicts

### ISSUE THREAD

**Issue by ExtrymasLTU** [xJon/Tekkit-2#40]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When fireing any projectile from ProjectE with R the projectiles do not fire. Oddly even if you change keybind to any other free key they still do not fire.
The only fix we found is if you disable Sort Inventory key then they fire.

**Comment by xJon** [comment]
It seems to work fine if I reassign either the inventory sort key or the fire projectile key?

**Comment by Fireflexor** [comment]
i also changed the inventory sort key and it worked fine, although i somehow turned a zombie into a horse which shouldn't be possible since they're in different pools for enemy randomisation

**Comment by xJon** [comment]
Fixed (for new installations) in `1.0.1`, new default is `Y`.
