### ISSUE TITLE
Creeper explosions and bounding boxes

### ISSUE THREAD

**Issue by Taliviere4586** [xJon/Tekkit-2#42]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**:  Yes
- **Did you add any additional mods**: No 
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

A clear description of what the issue is.
Upon a creeper explosion happening the server started freaking out and had continously spammee console for the last 8 hours

![Untitled](https://user-images.githubusercontent.com/112741053/188274320-24610fb0-0f5c-41bc-b5ed-2ab99a420b95.png)

**Comment by xJon** [comment]
Please post the server log using https://mclo.gs/.

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if requested!
