### ISSUE TITLE
Copper Ore uses in Washing Factory crashes the game

### ISSUE THREAD

**Issue by ExtrymasLTU** [xJon/Tekkit-2#44]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/a93BYmH https://mclo.gs/rUordBw

**Describe the issue**

Looking at uses for Copper Ore and clicking on uses in Washing Factory crashes the game.
![564](https://user-images.githubusercontent.com/53148680/188286328-7e922455-dbb0-413b-a62b-dc6e9bdd774e.png)

**Comment by xJon** [comment]
Thanks for the report! I can't reproduce this using the latest version of the modpack (`1.0.1`), neither on singleplayer nor multiplayer.
![image](https://user-images.githubusercontent.com/8945347/188286497-c8423c49-7047-452d-84b9-71ec005608e4.png)

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if requested!
