### ISSUE TITLE
Industrial Foreging Latex Processor Eats buckets

### ISSUE THREAD

**Issue by TotallyNotAGhost** [xJon/Tekkit-2#46]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

if a latex processing unit has less than a bucket left of room in it's latex tank then putting a latex bucket in there will destroy the bucket.

https://www.youtube.com/watch?v=-VM4McAUCEg

**Comment by xJon** [comment]
Huh. Any chance you can forward this report to this repository? https://github.com/eve0415/IFPatcher/issues

**Comment by TotallyNotAGhost** [comment]
I can repost this over there.

**Comment by eve0415** [comment]
Hello.

Thank you for reporting.
I've patched the issues and version 2.1.0 will be available at [CurseForge site](https://www.curseforge.com/minecraft/mc-mods/ifpatcher).

**Comment by xJon** [comment]
Fixed in `1.0.2` thanks to @eve0415 :)
