### ISSUE TITLE
Server crash when updating to 1.0.1

### ISSUE THREAD

**Issue by rilliko** [xJon/Tekkit-2#47]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

As title suggests, server complete crash when updating to 1.0.1 (something to do with FML security wrapper, no log available) additionally, when manually updating the 1.0.0 server and copying the world over it successfully starts however the world COMPLETELY breaks, chests change to cobblestone, many random blocks change, wood pipes become quarries, ect.

**Comment by xJon** [comment]
Tis shouldn't happen when updating, as the block/item ID data cannot just change in an update (unlike old versions of modded Minecraft). This can only happen if your save got corrupted. Either way, can I ask why is a crash or latest log link not applicable?

**Comment by rilliko** [comment]
Apologies Jon, I believe the issue might have been caused by /fml confirm not running on the server correctly - going to try launching the world in single player to process the fml changes then copying that world onto the server
