### ISSUE TITLE
MAtmos OS incompatibility crash

### ISSUE THREAD

**Issue by DatGurney** [xJon/Tekkit-2#48]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/G60t7QF
-  single player crash: https://mclo.gs/q1xInsY

Running on arch linux. My friend on windows did not seem to have an issue

**Describe the issue**

When trying to join a server and single player world, matmos causes my game to crash and doesnt let me join the world. disabling matmos lets me join the server just fine. Was not having this issue on 1.0.0, just after updating to 1.0.1

**Comment by xJon** [comment]
This is a bug with MAtmos that was reported over https://github.com/makamys/MAtmos/issues/24.
For now you can manually revert the mod's version to the previous one - you can get it from https://www.curseforge.com/minecraft/mc-mods/matmos/files/3949999.

**Comment by xJon** [comment]
Fixed in `1.0.2` thanks to @makamys :)
