### ISSUE TITLE
Galacticraft Rocket Despawns on server

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#49]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://www.skywereindustries.com/Downloads/Tekkit2/latest.zip
Edited: https://mclo.gs/atLp3vC

**Describe the issue**

Galacticraft rockets are launching but as soon as they hit the barrier for map transition they despawn and we fall back down to sol, a player was at a space station during the update and sadly cannot leave the station due to this bug, I have posted two logs in a zip, one is the full log, the other is a snippet from the mod capture breakdown making your life easier to find the correct issue. 

Everything else so far has been fine, just galacticraft. We did restart the server and reset configs just incase but nothing worked as of right now, we are patient!

Sorry it is not in pastebin.

**Comment by xJon** [comment]
Seems like an issue on servers only for some reason. Thanks for the report, hopefully will be able to resolve this soon.
For now, whoever is stuck in space, you can watch The Martian for inspiration. (or use `/forge setdimension`)

**Comment by SparksSkywere** [comment]
I am the only one with OP and the owner, but before you commented he ended up becoming space debris and burned coming down back to sol.

pov the rest of the server watching him fall: https://www.youtube.com/shorts/Pji9fObpSpM

Thank you for the amazing reply, we all had a good laugh over it!

**Comment by xJon** [comment]
Fixed in `1.0.2` thanks to @ROMVoid95 and @ACGaming!
