### ISSUE TITLE
Redstone Engines are not working

### ISSUE THREAD

**Issue by ElVincenco** [xJon/Tekkit-2#51]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Redstone Engines are not working and are looking upright when placed against a Quarry or other part. When you remove the Redstone engine the flying pixels are black and purple

**Comment by xJon** [comment]
They are unable to power a quarry, and the missing particle textures is a current issue with BuildCraft that's already known.
Thank you nonetheless for the report and feel free to get more help over https://discord.com/invite/technic for how to power a quarry!
