### ISSUE TITLE
Forge Mod Loader detected missing registry entries

### ISSUE THREAD

**Issue by thomasflrs** [xJon/Tekkit-2#52]
After updating Tekkit 2 to 1.0.1 and trying to start a world, I get the message "Forge Mod Loader detected missing registry entries."
![Screenshot (29)](https://user-images.githubusercontent.com/44059612/188323835-d7bdbe41-64b0-4600-b299-4fe81fbb39c6.png)

**Comment by xJon** [comment]
You can safely press `Yes` and continue, those are simply no longer included :)
