### ISSUE TITLE
[1.0.1] [Server] Galacticraft Rockets break in space (invalid side SERVER)

### ISSUE THREAD

**Issue by Pulz-TCP** [xJon/Tekkit-2#53]
**Basic details**
- **Did you add any additional mods**: no

**Describe the issue**

Using the provided server download, fresh and unmodified:

As of the recent update (that is to say, this was not a problem previously), the rocket breaks in space at the point where it would otherwise bring up the planet selection GUI.
[Here](https://mclo.gs/NzlxBe0) is an error that appears in console at this time.

Not quite sure how this slipped past.

**Comment by xJon** [comment]
https://github.com/xJon/Tekkit-2/issues/49
