### ISSUE TITLE
Logistic Pipes doesn't work with Charset's barrels

### ISSUE THREAD

**Issue by StarskyXIII** [xJon/Tekkit-2#54]
I tried to use Provider Logistics Pipe to extract items from barrels of Charset.
But it seems do nothing for me.
Then I tried to extract items from chest, it works well for me.
If Provider Logistics Pipe connect to barrels, it will cause other sides not work.

Test video
https://drive.google.com/file/d/16qWsMAotbdlMiaAZpR0OyeymWJRpKUG2/view?usp=sharing

Modpack version: 1.0.1

**Comment by xJon** [comment]
Can you test whether this is still an issue in the `1.0.2` modpack update? :)

**Comment by StarskyXIII** [comment]
Yes, it is still an issue.

**Comment by xJon** [comment]
Do you play singleplayer? Can you share your game log from that session? You can use https://mclo.gs/

**Comment by xJon** [comment]
Also, as a workaround you can try to use the Black Hole Units from Industrial Foregoing.

**Comment by StarskyXIII** [comment]
This is my [debug.log](https://mclo.gs/ab1yLQs) at that time.

This issue happen in both side.
And it works well with Black Hole Units & Controller 2.0

**Comment by xJon** [comment]
Could you also attach the `latest.log`?

**Comment by StarskyXIII** [comment]
https://mclo.gs/H1cQRuW

**Comment by xJon** [comment]
I don't see anything particular about it in the game log but I will forward this incompatibility, thanks for the report!

**Comment by xJon** [comment]
Further testing shows that Charset barrels have specific sides for insertion and extraction: extract from bottom, insert to top or back side. This can probably be changed with a future Logistics Pipes update but I wouldn't consider it to be a bug :)

**Comment by DatGurney** [comment]
It seems that Logistics pipes also doesnt detect more than one stack in the barrel. Each item in my LP system is only showing 64 that is within a barrel. This is with a provider pipe on the bottom and an itemsink module on the top. These both pull and push fine

**Comment by xJon** [comment]
@DatGurney In that case, could you report that over Logistics Pipes' issue repository (https://github.com/RS485/LogisticsPipes) maybe with some extra detail, as a feature request? Thank you :)

**Comment by xJon** [comment]
Will be included in the next pack update thanks to https://github.com/RS485/LogisticsPipes/commit/78cc088c9cb8420e918bd2928eafd4c2887242e5

**Comment by xJon** [comment]
Should work in `1.0.5` :)
