### ISSUE TITLE
Missing Map?

### ISSUE THREAD

**Issue by ljboxf** [xJon/Tekkit-2#55]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (detail) no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
Upon updating to the latest release of tekkit 2 it seems like there's a few issues with the map.

A clear description of what the issue is.
https://i.imgur.com/okDAdrQ.png
https://i.imgur.com/O9unoCN.png

**Comment by xJon** [comment]
Does this still happen if you reenter your world?

**Comment by ljboxf** [comment]
Just going to give it a go

**Comment by ljboxf** [comment]
Ah seems like after reentering it's working all fine and dandy

**Comment by xJon** [comment]
In case this happens again, feel free to reopen the issue and provide a game log :)
