### ISSUE TITLE
Loot Ball (Project E)

### ISSUE THREAD

**Issue by wiglet1** [xJon/Tekkit-2#56]
In previous versions of Tekkit, tools such as the destruction catalyst from Project E/Equivalent Exchange would take all items mined and condense them into a single black orb called a loot ball. Without this, all items mined are scattered at your feet which causes a considerable amount of client side lag.

**Comment by xJon** [comment]
I wouldn't call it a bug but a missing feature from Project E in 1.12.2. Not sure if it's a feature in other versions of Project E.

**Comment by Lumpous** [comment]
The Gem of Eternal Density is a tool added by ProjectE. It is used to turn items with a lower EMC than the target into Iron, Gold, Diamonds, Dark Matter, or Red Matter. It does this only while active and on the user's hotbar.

https://ftb.fandom.com/wiki/Gem_of_Eternal_Density_(ProjectE)

**Comment by wiglet1** [comment]
> The Gem of Eternal Density is a tool added by ProjectE. It is used to turn items with a lower EMC than the target into Iron, Gold, Diamonds, Dark Matter, or Red Matter. It does this only while active and on the user's hotbar.
> 
> https://ftb.fandom.com/wiki/Gem_of_Eternal_Density_(ProjectE)

With all due respect, Lumpous, this is pretty much irrelevant since the lag spike occurs from the dropping of hundreds of blocks at the player’s feet. The gem of eternal density only condenses the items once they are in the inventory. It doesn’t solve the problem unfortunately.

**Comment by Lumpous** [comment]
I'm sorry, but it is very much relevant to your question.
If you had taken a closer look at the given page, you would have noticed that there is one item that is very suitable for combination: the Black Hole Band.

https://ftb.fandom.com/wiki/Black_Hole_Band_(ProjectE)

Since the loot ball is not available, this would be the only way to suck in items AND condense them - however, you would now have to use 2 items to do this.

**Comment by wiglet1** [comment]
I have the black hole band, unfortunately it just expands the range from which the player can pick up item-drops and doesn't place the items directly into the player's inventory. In fact, if you read the article that you linked you will find it even says so. 

> It is used to collect dropped item entities within a radius of about 6 blocks when activated

So, items are still dropped at the player's feet, yielding a major lag spike. i.e. neither the black hole band nor the gem of eternal density fix the problem.

**Comment by Munchy907** [comment]
https://github.com/sinkillerj/ProjectE/commit/1d3f1479e6647ba25f8fc89c61ae04cc68cca130

**Comment by xJon** [comment]
As this feature was purposefully removed from ProjectE, I'll close this suggestion.
@wiglet1 Feel free to reach out to them and inquire about it, and thank you nevertheless for the suggestion!
