### ISSUE TITLE
Crash Issue on tekkit 2

### ISSUE THREAD

**Issue by xTakeAwaytjuhx** [xJon/Tekkit-2#57]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/9lbvyoN

**Help needed**

So whenever I am playing Tekkit 2 on a server I sometimes randomly crash for no reason as far I am aware of, it happens on any random moment not when doing anything particular, the issue only has started appearing today (05/09/2022).  I am also not the only person who this has happened to, a friend of mine has the same issue.

**Comment by xJon** [comment]
Strange, not much can be learned from the crash report. Did you happen to change any settings for the minimap (e.g. enabling the mob radar)?

**Comment by xTakeAwaytjuhx** [comment]
Nope, I reinstalled the modpack too and the issue keeps appearing for me, but I always can take a second look at my settings.

**Comment by xJon** [comment]
Can you reproduce the issue in any way? Is it only happening on one server?
Perhaps you can try to manually remove the minimap mod and see if you can reproduce the issue?

**Comment by xTakeAwaytjuhx** [comment]
As far I am aware of not, It only happened to me at random intervals and even when I am just afk, so I don't think there is any way I can reproduce the issue. But i'll try removing the minimap and see if it keeps happening after.

**Comment by Taliviere4586** [comment]
is this the unknown mod error?  ive been getting it all day today specifically when teleporting.

**Comment by xTakeAwaytjuhx** [comment]
Yea it is, but for me it isn't with teleporting, it's fine for now tho been playin' fine for over an hour now.

**Comment by xJon** [comment]
@xTakeAwaytjuhx So is it not happening without the minimap mod installed?
@Taliviere4586 Can you try to manually remove the minimap mod and try to reproduce it?

**Comment by Taliviere4586** [comment]
https://mclo.gs/EeCvfz8 Client crash report
https://mclo.gs/PFJCMMT Server log of when i crash
Not just teleporting more specifically loading in logistics pipes chunk wise

**Comment by xTakeAwaytjuhx** [comment]
@xJon so far yea, but if I run into the issue again I'll let you know.

**Comment by xJon** [comment]
@xTakeAwaytjuhx Is this issue still happening?

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
