### ISSUE TITLE
Server don't start after updating to version 1.0.2

### ISSUE THREAD

**Issue by ElVincenco** [xJon/Tekkit-2#59]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: https://mclo.gs/aXtyfJQ

**Help needed**

Played only on version 1.0.1 before. Created a backup, downloaded the version 0f 1.0.2 and extracted the zip. Restarted the server but now it won't start.

**Comment by xJon** [comment]
Seems like the installation is gone wrong, how did you update the server?
You'd need to extract the zip, copy over the world and use the launch script.

**Comment by Vleupold** [comment]
I use AMP as hosting tool on a LinuxVM. I stoped the server, copied the zip, unziped it and startet the LaunchServer.sh

**Comment by xJon** [comment]
Copied which zip?

**Comment by Vleupold** [comment]
The ZIP from the new server files

**Comment by xJon** [comment]
Did you copy over the previous world folder? Just making sure you didn't use a backup zip file, as they are not meant to be extracted.

**Comment by Vleupold** [comment]
Nope. I got my folder called tekkit2 inside is the Server stuff from the ZIP and my world folder. I just copied the new server ZIP inside there, extracted it and tried to restart it with the new update

**Comment by Lumpous** [comment]
By doing so you run the risk mods, that do contain their version number within their filename, are now there multiple times.

Avoid this by always placing server updates always in a new folder and move the old world into the new folder.

**Comment by ElVincenco** [comment]
Ah yes i understand. I thougt Ubuntu would overwrite them but maybe there are some failures happening. I will follow your Tip with just creating a new Folder! Thank you

**Comment by Lumpous** [comment]
Ubuntu handles the files as expected.
Same filenames will be overwritten, new files will be simply added to the folder then.
That happens when mods in new versions are included then. 😉

**Comment by ElVincenco** [comment]
But then i dont understand why this crash happend... But its fine world not gone and just created the server new as you mentioned !

**Comment by Lumpous** [comment]
Assuming from version 1.0.1 to 1.0.2 buildcraft has updated.
In version 1.0.1 there was bc_v1000.jar
In version 1.0.2 there was bc_v1001.jar

If you simply unpack the new mod pack version, you would end up having both versions of buildcraft within the mods folder then.
The one from v1.0.1 and the new one from v1.0.2

That will cause a crash.

**Comment by ElVincenco** [comment]
Now i understand what you mean! Yes that makes sense. Thanks for your help! maybe an update script would be nice so you don't have to move the world folder and create a "new" server every time
