### ISSUE TITLE
BuildCraft Fragile Lava Shard doesn't consume on right-click use 

### ISSUE THREAD

**Issue by Untick3** [xJon/Tekkit-2#6]
If you acquire a "Fragile Lava Shard" from BuildCraft, you can just right click a Geothermal Generator, using the shard filling 1 bucket of lava into the generator but the shard doesn't get consumed, making you able to spam it and fill up as many generators as you would want.

You can acquire a shard by breaking an Iron Tank filled with some lava, for example.

Tested in both single-player and multi-player.

 -- Modpack wasn't modified.

**Comment by xJon** [comment]
Will disable the shards in the next update.

**Comment by xJon** [comment]
Fixed in `1.0.1`.
