### ISSUE TITLE
Geothermal Generator and Pipe Interactions

### ISSUE THREAD

**Issue by Yuzeen** [xJon/Tekkit-2#60]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

It seems like geothermal generators isn't accepting lava cans/lava buckets. I've tried using redstone engine w/ wooden extraction pipe and placed pipes going into the geothermal generator in various positions, but the entities won't go into the correct slot of the generator. Is this a known issue?

**Comment by xJon** [comment]
I'm pretty sure it needs to accept them from a specific side? I remember players discussing the correct way of doing this over Technic's channel, perhaps you could ask there, but there shouldn't be a known issue :)

**Comment by Yuzeen** [comment]
Hi,

Thank you for your reply! I tried every side and unfortunately no results. Weird since this method works with every other ic2 machine i've tested except for geothermal

**Comment by xJon** [comment]
I think they only accept liquid lava actually, you can use a Forestry Bottler to empty lava cells/buckets. There are more creative ways of doing it though, you can ask over Discord :)

**Comment by Speiger** [comment]
Looks like i wanted to discurage item insertion and "Disabled" the fluid slot by default.
Though it looks like you can enable it via machinetool with a automation upgrade.

**Comment by PawnixHere** [comment]
Will enabling it with a machine tool with an automation upgrade allow logistics pipes to feed lava cells into them?

**Comment by Speiger** [comment]
it should

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
