### ISSUE TITLE
Cable and machines positions reset after going to the nether.

### ISSUE THREAD

**Issue by leafnie** [xJon/Tekkit-2#62]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)** not applicable

**Describe the issue**

When coming back from the nether, all the cables and machines I had were "reset" in orientation. Had to break and replace a few cables to get them working - the original item dropped from what looked like an uninsulated copper wire.
![image](https://user-images.githubusercontent.com/112996037/188771885-c9d6beb5-1e9d-44eb-8587-f68459fd18a2.png)

**Comment by xJon** [comment]
Did a relog solve it?
Can you provide a full game log from that session using https://mclo.gs/ ?

**Comment by embeddedt** [comment]
Does this only happen to IC2 items? There is a long-standing IC2exp bug on 1.12 where cables disconnect after changing dimensions/reloading, it may affect Classic too.

**Comment by Lumpous** [comment]
I can confirm this is happening from Packversion V1.0.0 on until V1.0.3 on Servers everytime Dimensions are changed.
Thankfully it appears to be only a visual glitch not affection connections and power-transportation.
EU-Reader confirmed functionality of those visually disconnected cables.
Relog into the server solves this issue.

**Comment by xJon** [comment]
I tested this on a local server going in and out of a Nether portal and couldn't reproduce this, the cables took maybe half a second and then they updated properly. Strange.

**Comment by leafnie** [comment]
Fixed itself after a game reboot.

**Comment by Jaari** [comment]
Oh, didn't expect to see that issue again, back in 1.6.4 you had this as well, but it was actually all disconnected.
