### ISSUE TITLE
Mod addition question

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#63]
Hello,

Just wandering what the stance on adding certain mods to the pack that would make sort of sense to tekkit, I know there are hundreds of other packs out there with mods already but I am just wandering what ideas / additions maybe done to tekkit for the future.

I also would ask if a mod I used a lot back when tekkit was in use (injected into my own servers for friends) "Refined Storage" not too OP but helps large factory setups.

**Comment by Lumpous** [comment]
Tekkit 2 already includes 2 mods that can handle storage management to an extend.
Logistics pipes and project red.

Refined storage is a good mod, but another mod for storage management feels odd.
Also the RF theme does not really fit to tekkit 2.
Personal opinion of mine.

**Comment by SparksSkywere** [comment]
> 

Fair enough, just mostly a question to see what others thought, doesn't stop me making changes to the modpack my end on the server but just thought on it while going through the list of additions.

**Comment by xJon** [comment]
Yeah well said by @Lumpous, but feel free to make changes on your end and play the game however you want :)
