### ISSUE TITLE
Launching Error

### ISSUE THREAD

**Issue by SkylordMinecraft** [xJon/Tekkit-2#64]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes 1.8.0_341 64 -Bit
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: Heres the techinc launcher log: https://pastebin.com/wy54guP2
**Describe the issue**

When clicking play from the technic launcher, After it gets to "Examining Java Runtime" It doesnt progress past 0% and gives me the error "Error downloading a file for the following pack: Tekkit 2 Failed to get Mojang JRE information Please cunsult the modpack author."
![dfgdfgdfg](https://user-images.githubusercontent.com/113051216/188937071-2d6158ba-5236-4229-a5bc-72a7cd789cf2.PNG)

**Comment by xJon** [comment]
Seems to have been a temporary issue with Technic or Minecraft, has nothing to do with Tekkit 2, it should work now. Thanks either way for the report!

**Comment by SkylordMinecraft** [comment]
idk how to close an issue ;-;

**Comment by xJon** [comment]
Good job :)
