### ISSUE TITLE
BuildCraft fluid transport pipes & Binnie's Extra Trees not working?

### ISSUE THREAD

**Issue by hhans3n** [xJon/Tekkit-2#67]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

I can't seem to get BuildCraft fluid transport pipes to work with things like Binnie's distillery and juice press, and I am unsure how else I can get fluids out of the juice press. Any help is appreciated!

**Comment by PaziGamer** [comment]
Are you sure you use the wooden fluid pipes with redstone engines attached to them, to pump the liquid out from the tanks or machines? They work for me just fine with the Binnies machines, before and after the last update.

**Comment by hhans3n** [comment]
Thank you so much! I have been going crazy trying to figure this out.

**Comment by lividsubset3** [comment]
Buildcraft got updated if you want a more advanced setup and more compact use the pulsator from buildcraft silicon. They act as a red stone engine and can be toggled manually or with gates.

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
