### ISSUE TITLE
Random Railcraft crashes (Client)

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#69]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/6zQJT4D

**Describe the issue**

Randomly while on my server this crash report comes up, I can go back to the main menu  and return to the server, so it does appear to be client only, restarts can help remove the issue but it keeps coming back, any thoughts?

**Comment by ACGaming** [comment]
The crash report is mentioning a Railcraft Void Chest at the coordinates -17, 69, 367. Can you try replacing/relocating it and see if the issue persists?

**Comment by SparksSkywere** [comment]
> The crash report is mentioning a Railcraft Void Chest at the coordinates -17, 69, 367. Can you try replacing/relocating it and see if the issue persists?

I removed the chest indefinately as it keeps crashing even replaced.

**Comment by SparksSkywere** [comment]
Whelp it happened again but this time is unknown: https://mclo.gs/NjWNsR5 

Also I like how it says I am using windows 8,1 but in reality I am on windows 10

**Comment by xJon** [comment]
@SparksSkywere Can you report all of your crash reports after removing the chest?
Also, can you report whether the crash is still happening without the minimap mod installed?

**Comment by SparksSkywere** [comment]
> @SparksSkywere Can you report all of your crash reports after removing the chest? Also, can you report whether the crash is still happening without the minimap mod installed?

Logs from my client in a Zip file: https://www.skywereindustries.com/Downloads/Tekkit2/Clientlogs.zip As of right now I have not done anything to the minimap

**Comment by xJon** [comment]
Those crash reports still mention a Railcraft Void Chest at the coordinates `-17, 69, 367`?

**Comment by ACGaming** [comment]
@SparksSkywere You‘d need to actually place another block there or even replacing and breaking the void chest to toggle a block update at this position if it still gets mentioned in crash reports!

**Comment by SparksSkywere** [comment]
I have deleted the chest, replaced its block area, waiting on a crash.

**Comment by SparksSkywere** [comment]
After a few hours of playing, some mods disabled and had others sending me logs in the last few hours, have fun with the logs, hope I am not being annoying too much!

Had others crash, their logs are:
https://mclo.gs/5BGP1dn
https://mclo.gs/OcWwrYn
https://mclo.gs/SPCcMOh
https://mclo.gs/3p4ZQzO

My logs again:
https://mclo.gs/bx97kWM
https://mclo.gs/yD2d4Lv
https://mclo.gs/yWzcKC8

**Comment by SparksSkywere** [comment]
Removing the map did not work, computers still crashed.
So a day of testing with lots of ideas and going through many things, we have found some culprits to the issue

- Player models are spawned multiple times and classed as "Unknown" which causes the crashes, such as the one provided by a player: Retry entities: 3 total; [EntityLatchedRenderer['unknown'/2101909, l='MpServer', x=-1.76, y=64.00, z=0.48], EntityLatchedRenderer['unknown'/2106662, l='MpServer', x=-142.67, y=67.00, z=486.75], GCEntityOtherPlayerMP['blikakis'/40366, l='MpServer', x=-142.67, y=67.00, z=486.75]]

We located the entity and could not remove it, though a reload of the server will clear all these entities, we tested to see about unloading and reloading of chunks when these happen, to which yes, when a chunk is reloaded and this missing entity is detected it will cause a crash.

- I have attempted to load in many cleanup tools to stop the crashes, a plugin called CatLagClear managed to help but this cleaned up the server every 10 mins, not exactly the best because I have to use a plugin loader called Sponge so this makes me instantly in the fault as it is not what you originally made for the server, but I am trying many ideas.

So something is causing these creations of entities when players disconnect from the server and well clients are not cleaning up the players, this is theoretically what I see causing the issue but cannot pinpoint the crashes just yet, we will keep looking into this to find the issue, we are also removing and adding mods on clients to help.

**Comment by xJon** [comment]
@SparksSkywere Does disabling `enableLatchedRendererSpawn` over the `ichunutil.cfg` file have any effect on this?

**Comment by SparksSkywere** [comment]
Still got the crash even with the enableLatchedRenderSpawn set to 0 on the client side.

So I assume it is to do with GCEntitiyOtherPlayerMP

**Comment by xJon** [comment]
In this case, can you report this issue over https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues with all of the information you collected during troubleshooting?

**Comment by xJon** [comment]
I'm unable to reproduce this issue but it could just be rare, will keep it open.

**Comment by SparksSkywere** [comment]
> Can you check whether this issue is still happening in version `1.1.0` of the modpack?

I have updated my server and informed the players.

**Comment by SparksSkywere** [comment]
> Any update on this? Also note that `1.1.1` was released :)

Barely anyone has been on, but I haven't crashed, although I am having real issues with server lag and it isn't down to the hardware, it is 100% minecraft. I might have to reset the world.

**Comment by xJon** [comment]
Some players reported better performance in the latest versions, might be worth a try

**Comment by SparksSkywere** [comment]
> Some players reported better performance in the latest versions, might be worth a try

As of right now in v1.1.2:

1. The Morning Star does not crash the game anymore
2. Were still experiencing lag with the following:
![image](https://user-images.githubusercontent.com/34066194/198871642-6da18065-d969-420b-9ea9-043559c0e916.png)
3. Most crashes have been fixed but still getting the occasional server crash (I will create tickets if more of these crashes happen)

Overall there is a lot fixed so I am happy to report players are not crashing!

**Comment by SparksSkywere** [comment]
Just leaving this here for incase you may think server hardware is causing it: 

![image](https://user-images.githubusercontent.com/34066194/198871781-1882ba58-9f89-478a-a9ea-f59b4398b94e.png)

**Comment by xJon** [comment]
Glad a lot of the issues were resolved! In regards to performance, I don't have much experience as a server admin. I'd recommend using tools such as LagGoggles and/or Spark for profiling. Also chunk pregeneration can help.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
