### ISSUE TITLE
Cannot remove upgrades from IC2 machines

### ISSUE THREAD

**Issue by Rishum-P** [xJon/Tekkit-2#7]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: not applicable

A few players have reported that IC2 upgrades, such as the transformer upgrade, cannot be removed from machines even if ALT is pressed. Remapping the key does not work either. 

Changing the following setting: `B:enableKeysInGuis` from false to true in the IC2 config seems to fix the issue. Possibly should be changed in a future pack update.

**Comment by Speiger** [comment]
IC2C Author here.
This is kinda a "Anti Punishment system" in place.

Thought is, if you take transformer upgrades out on accident what happens? IT BLOWS UP.
They idea here is that you can no longer lose machines due to accidents like this specific case. (Upgrade containers where you don't see the items)

I am not going to change that because it is intentional, and will stay that like that.

**Comment by Rishum-P** [comment]
Isn't that the point of having to press Alt, though? If not, then the tooltip is misleading and should at least be changed.

**Comment by Speiger** [comment]
Yes it is the point of having to press that key. I just explained why I did it that way.
And keys in guis has to be on for that.

Sadly there is no real way to do it otherwise...

**Comment by xJon** [comment]
I think the main issue is that disabling `enableKeysInGuis` is not really intended for use. I will make sure it's enabled in the next update, just feel free to reassign jetpack key bindings for example so it doesn't conflict when searching in HadEnoughItems.

**Comment by PawnixHere** [comment]
If you refuse to delete the tooltip for which ALT button to press, which is extremely misleading at best and poor practice, make it so that a machine that is turned off and isn't connected to power can have its transformer upgrades removed like any other upgrade.

**Comment by Speiger** [comment]
You know what I am not dealing with this argument anymore
@GregoriusT can justify that feature since he was the one who effectively got me to put it in.

So greg your point to justify it.

**Comment by GregoriusT** [comment]
Speiger change the Tooltip to tell people to enable that enableKeysInGuis thing, that way they at least know how to enable the ALT key, and THEN if its enabled, show the original press ALT tooltip. This is clearly just a misleading tooltip issue and not an actual Feature Issue.

Also super dumb question, cant you just wrench the Machine to dismantle it and you will get all upgrades back?

**Comment by Rishum-P** [comment]
I don't understand why there is even any argument. The feature is 100% good and should be kept. The only issue here is a modpack (not mod) issue about changing the config setting for the next pack update.

I think the confusion, that caused the argument was that the first reply seemed like you were opposed to the enabling of the config option instead of just explaining why the feature exists, which there are zero issues with.

**Comment by GregoriusT** [comment]
Another Idea would be that the Tooltip could tell people "Use Wrench to dismantle Machine to retrieve Transformer Upgrades".

The only Issue is that the Tooltip literally lies to people instead of telling them what to do.

**Comment by Speiger** [comment]
> Also super dumb question, cant you just wrench the Machine to dismantle it and you will get all upgrades back?

Yes the inventory drops always. This is just a screen issue.


> Speiger change the Tooltip to tell people to enable that enableKeysInGuis thing, that way they at least know how to enable the ALT key, and THEN if its enabled, show the original press ALT tooltip

Nah the enableKeysInGuis is enabled by default.

> Another Idea would be that the Tooltip could tell people "Use Wrench to dismantle Machine to retrieve Transformer Upgrades".

This would require a major rewrite and a lot of extra code. Which since the mod is only in "Bugfix state" is way to big of a change.
The mod is AS IS in terms of features, and that includes that.

**Comment by GregoriusT** [comment]
Wait why was the enableKeybindsInGuis false in the first place for that Modpack?

**Comment by Rishum-P** [comment]
It was just a bug, and I'm guessing they never knew it would cause this issue. All this issue is, though, to suggest that the option is enabled for the next Tekkit 2 update, which Jon said it would. The discussion turned into something more complex.

**Comment by Speiger** [comment]
> Wait why was the enableKeybindsInGuis false in the first place for that Modpack?

Jetpack + JEI search

**Comment by xJon** [comment]
Indeed `enableKeybindsInGuis` was disabled due to trying to search in JEI whilst wearing a Jetpack and it was quite annoying, but I understand that feature is needed for other gameplay reason so it'll be reenabled.

**Comment by xJon** [comment]
Resolved in `1.0.1`.
