### ISSUE TITLE
Request logistic pipes

### ISSUE THREAD

**Issue by ElVincenco** [xJon/Tekkit-2#70]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

The Request logistic pipe sometimes not deliver the items. When requestet you see them comming trough the pipe but they just disapear and are not in the chest under the Request pipe. A server restart helps then. I cant say when this issue occurs directly.

**Comment by xJon** [comment]
Could you report this in detail directly to the mod author? Over https://github.com/RS485/LogisticsPipes/issues

**Comment by ElVincenco** [comment]
Will do, thanks! Did you disabled the RF pover provider and Pipe modules for this modpack or is this from the Logistic Pipe team disabled?

**Comment by xJon** [comment]
It was never implemented in 1.12.2 unfortunately, but hopefully will be enabled in a future update!

**Comment by ElVincenco** [comment]
Ah okay! Yes this would be verry nice
