### ISSUE TITLE
Transporting Forestry Saplings through certain BuildCraft pipes causes world corruption

### ISSUE THREAD

**Issue by tobylee1112** [xJon/Tekkit-2#72]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: https://pastebin.com/y2uQfcQr

**Describe the issue**

I transported Apple Oak Saplings from the Forestry mod using the Diamond Transport Pipe from BuildCraft. Upon doing so my game crashed and my world was corrupted. It seems to work fine when using other transport pipes except those that filter items.

**Comment by xJon** [comment]
Can you reproduce this behavior?

**Comment by tobylee1112** [comment]
> Can you reproduce this behavior?

Yes, I tested it on a new creative world with the same setup. I tried also it with only wooden pipes and it had no issues. Only when I switched to diamond pipes and it corrupted the world.

**Comment by xJon** [comment]
Can you please report this in detail over https://github.com/BuildCraft/BuildCraft/issues ?

**Comment by Lumpous** [comment]
I tested it with unidentified saplings from forestry and binnies extra trees in creative.
Result is the diamond pipe from BC is unable to sort them at all - at least without any crashes.
https://lumpous.de/tekkit2_72.mp4

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

forestry_1.12.2-5.8.2.422.jar
binnie-mods-1.12.2-2.5.1.204-technic1.jar

**Comment by Lumpous** [comment]
https://github.com/BuildCraft/BuildCraft/issues/4683#issue-1369015542

**Comment by tobylee1112** [comment]
Here's the video of how I reproduced the corruption: https://youtu.be/Ckp0g1TXmts

**Comment by xJon** [comment]
@tobylee1112 Can you report that over https://github.com/BuildCraft/BuildCraft/issues as a separate issue?

**Comment by xJon** [comment]
As BuildCraft is not in active development, there's not much else I can do. It is open licensed though, so anyone could PR new improvements. Will close for now.
