### ISSUE TITLE
Black Hole Unit from Industrial Foregoing not usable with Item Translocators from Translocators

### ISSUE THREAD

**Issue by doublehdx** [xJon/Tekkit-2#73]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:   no

**Black Hole Unit not accepting items from Translocators**

If i try to get Item from a Storage Solution to the Black Hole Unit with Translocators it only allows to transfer one item. After that it is not able to transfer more.

**Comment by xJon** [comment]
If you think this is an issue with the BHU from IF, you can try to report it to [IFPatcher](https://github.com/eve0415/IFPatcher/issues), but if it's an issue with the Translocators unfortunately I'm not sure that mod is still in active development but you can try to report it over https://github.com/TheCBProject/Translocators/issues.
