### ISSUE TITLE
Adjusting EMC-Value of Oranium Ore

### ISSUE THREAD

**Issue by Lumpous** [xJon/Tekkit-2#74]
Considering the fact that uranium ore has an EMC value of only 2048, and the fact that "near-depleted uranium cells" can be
which can then be used in a breeder reactor, this low EMC value is not correct.

Using 1 uranium will produce 8 near depleted rods + 1 uranium cell = 8 uranium cells (so a bit of coal dust is needed).

So it seems to me that an increased value *8 is more correct.
*7 also seems acceptable considering that few additional materials are needed.

**Comment by xJon** [comment]
So you're saying that the EMC value of uranium is too cheap for the amount of energy it provides?
I think I'll probably adjust it to match the Tekkit Classic value of 4096 EMC.

**Comment by xJon** [comment]
Changed in `1.0.5` :)
