### ISSUE TITLE
ReAuth Login issue

### ISSUE THREAD

**Issue by laylovv** [xJon/Tekkit-2#75]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no

**Describe the issue** when i try to do the reauth login it wont let me and keeps saying login failed - please try again

**Comment by xJon** [comment]
It's been working fine for me, did you migrate your account to a Microsoft account?

**Comment by laylovv** [comment]
might be the issue will try to look into it thanks for the help otherwise tho. :)

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
