### ISSUE TITLE
[Suggestion]: Railcraft Liquid Fuel Boiler - Fuel Type

### ISSUE THREAD

**Issue by lividsubset3** [xJon/Tekkit-2#76]
In buildcraft you can pump oil,  "crack" it into is sub properties and use.

If it would be possible to have the liquid fuel boiler accept these types of fuel? Not just ethanol. 

It would be nice to get a steam setup with the use of oil. And not just use liquid fuel generator. For both power generation and separate use for steam.

Ps. Love the pack, some great work. From my 2 days of game time already logged. I'm have been having a blast.

**Comment by xJon** [comment]
I don't believe it's possible to use all the BuildCraft oil/fuel types - this would require special integration from Railcraft? I don't have much experience with this but feel free to discuss this over Railcraft's [issue repository](https://github.com/Railcraft/Railcraft/issues) or [Discord](https://discord.gg/VyaUt2r) :)

**Comment by lividsubset3** [comment]
I feel that configuring the railcraft boiler might allow this to be possible but I will see what I can find

**Comment by lividsubset3** [comment]
What I have figured out so far is that railcraft does support those fuel types ->
```
public enum Fluids implements Supplier<Optional<Fluid>> {

    WATER,
    LAVA,
    FUEL,
    BIOFUEL,
    IC2BIOGAS,
    CREOSOTE,
    STEAM,
    BIOETHANOL("bio.ethanol"),
    COAL,
    PYROTHEUM,
    FRESHWATER,
    BIODIESEL,
    DIESEL,
    GASOLINE,
    OIL_HEAVY,
    OIL_DENSE,
    OIL_DISTILLED,
    FUEL_DENSE,
    FUEL_MIXED_HEAVY,
    FUEL_LIGHT,
    FUEL_MIXED_LIGHT,
    FUEL_GASEOUS,
    REFINED_OIL,
    REFINED_FUEL,
    REFINED_BIOFUEL,
    TREE_OIL,
    SEED_OIL;
    private final String tag;
```
But not sure on how say a configuration file might come in play.

Still doing some digging into it.

**Comment by AstoriaFloyd** [comment]
I have discovered why BC fuel does not work. It was added after the latest release, being extremely outdated, being from 2019. This could be solved by updating to a beta release.

**Comment by xJon** [comment]
@AstoriaFloyd See https://github.com/xJon/Tekkit-2/issues/99#issuecomment-1249558631

**Comment by AstoriaFloyd** [comment]
I see. In that case using Moretweaker and Modtweaker to add the buildcraft fuels to the boiler with custom values could also work.

**Comment by xJon** [comment]
If the newer version of Railcraft add support, I'd prefer to update to it instead for all of the benefits. Perhaps you could inquire over Railcraft's Discord: https://discord.gg/VyaUt2r

**Comment by xJon** [comment]
Railcraft was updated in version `1.1.0` of the modpack :)
