### ISSUE TITLE
IC2 recipe for IF plastic

### ISSUE THREAD

**Issue by ACGaming** [xJon/Tekkit-2#77]
An IC2 rubber furnace recipe for IF plastic would be very handy because it‘s annoying to handle rubber production twice for different mods.

**Comment by Lumpous** [comment]
The recipe to burn IC2C rubber down to plastic was removed on purpose.

**Comment by xJon** [comment]
As @Lumpous mentioned it's actually intentional to encourage separate progress for both mods, as by default their rubbers are ore dictionaried!
I think it's better to encourage players to fetch both types of rubber separately, but I can leave this open for discussions and opinions of other players

**Comment by ACGaming** [comment]
Weird flex but okay.

**Comment by xJon** [comment]
I think that both mods' introduction process is unique and that there is value in not merging them, but anyone who feels differently can remove this in `\scripts\tekkit2.zs` :)
