### ISSUE TITLE
Regular server crashes with version 1.0.4

### ISSUE THREAD

**Issue by ElVincenco** [xJon/Tekkit-2#78]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: [link to log](https://mclo.gs/WpR1rSZ)

**Describe the issue**

Server crashes randomly during playing. Logs says something about ViewEMC Error.

**Comment by xJon** [comment]
There's no crash report in that log - you can find them in the `crash-reports` folder.

**Comment by xJon** [comment]
Seems like it timed out - you'd need to profile your server and find out what's causing it. Unfortunately I don't have much experience running servers so I don't know how to help beyond that.

**Comment by ElVincenco** [comment]
Ok! Thanks for your help anyway
