### ISSUE TITLE
Suggestion: New EMC values for world generation items in Quark and RailCraft

### ISSUE THREAD

**Issue by b9005910** [xJon/Tekkit-2#81]
I would like to suggest new EMC values for world generation items in Quark and RailCraft.

Quark:
- Cave Crystals - Decorative Item - Found in Crystal Caves - EMC value would be high due to rarity. Or make the caves rarer to justify high EMC. Don't give crystal sheets EMC values. Same idea as glass panes.
-  Elder Prismarine - Decorative Item - Found rarely underwater - double EMC value of regular Prismarine. 
- Brimstone - Decorative Item - Found in Nether? - Make same value as nether brick? or another valuable nether item?
- Permafrost - Decorative Item - Found in Overworld? - Same idea as Brimstone?
- Glowcelium - Decorative Item - Found in Overworld? - Make it more valuable than Mycelium?

RailCraft
- Abyssal Stone - Make it same/similar values to vanilla stones (Granite, Diorite, Andesite)
- Quarried Stone - Same process. 

By A_British_Bloke

**Comment by xJon** [comment]
Good suggestion, although for now I might keep it as is as in my eyes these blocks are rare world generation first and decorative second.
More opinions are welcome!
(Also, anyone who already wants these to have an EMC value can do it in-game with `/projecte setEMC`)
Also, what's quarried stone? I can't find what you're referring to.

**Comment by xJon** [comment]
Added in `1.0.5` :)
