### ISSUE TITLE
Grammar issues with advancement descriptions and titles

### ISSUE THREAD

**Issue by PawnixHere** [xJon/Tekkit-2#82]
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

**BuildCraft -> How does this work again? -> Iron helmet**
Iron helmet is missing a title and description. Defaulting to "advancements.buildcraftcore.goggles.description" & "advancements.buildcraftcore.go"

The BuildCraft advancement **"Sealing Fluids"** description reads "...craft is dye..."
Is it supposed to read "...craft its dye..."?

The IndustrialCraft2 advancement descriptions for **"Storage Upgrade"** & **"Just Too Much".** The noun "Build" is followed up by vowel sounds; "MFE" & "MFS", not a consonant sound. The correct spelling is "an" not "a" for both advancements.

The IndustrialCraft2 advancement **"Better than Iron"** suggests that the player smelts refined iron, which is impossible and the advancement should probably read "Smelt An Iron Ingot".

**Comment by xJon** [comment]
These things should be discussed directly with mod authors, so feel free to discuss it respectively over https://github.com/BuildCraft/BuildCraft/issues and https://github.com/TinyModularThings/IC2Classic/issues.

**Comment by PawnixHere** [comment]
I wouldn't consider this a question, but you know best, chief.

**Comment by xJon** [comment]
I changed the label to a `question` because I'm reforwarding your feedback regarding the advancements.
If you have feedback about the label you can feel free to make a suggestion :)

**Comment by PawnixHere** [comment]
No feedback about it. Cheers for explaining :)

**Comment by xJon** [comment]
Also for extra context, these could probably be changed over the modpack's end but I wouldn't feel comfortable tweaking these assets myself - I'd prefer mod authors to figure that out.

**Comment by Speiger** [comment]
Small point here:
Unless its actual typos I have no issue with these kinds of reports,
but things like this where someone says "Emm Actually this is not perfectly correctly written in the most perfect way" in Karen voice.
No thank you, especially since the IC2 examples are not even reasonable since both ways are valid.

For now i just locked this issue for a "nice" way of saying to shut up. And a warning.
