### ISSUE TITLE
Blockcraftery framed blocks + glowstone doesnt work on server

### ISSUE THREAD

**Issue by DatGurney** [xJon/Tekkit-2#84]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Using glowstone on the blockcraftery framed blocks to make them glow doesnt work. I have tested this in single player and it worked fine but on my server does not work. will consume the glowstone light up for 1 tick but then goes back. breaking the block will return a glowstone dust but you can keep applying glowstone to the block when it doesnt light up. I had a look on their issue tracker and did see others having the issue with version 1.2.0 of the mod and was closed as fixed in later versions

![image](https://user-images.githubusercontent.com/19272345/190136758-3d071ac3-1ad1-4a73-a446-ec344933f55c.png)
![image](https://user-images.githubusercontent.com/19272345/190137309-a2284a2b-1951-4022-802c-aaf462741f13.png)
![image](https://user-images.githubusercontent.com/19272345/190136812-10edb5e4-3ab1-4ef6-b707-bb43010a6dba.png)

**Comment by Lumpous** [comment]
Is the server running any plugins or has any restrictions in place?
Or is this a "plain" server as downloaded without any further modifications?

**Comment by DatGurney** [comment]
I do have Dynmap forge installed, but have tested with the mod removed and still the same on a "plain" server

**Comment by xJon** [comment]
This is a known bug from 2019 unfortunately that never got fixed (https://github.com/MysticMods/Blockcraftery/issues/49). The mod is open source though, so if someone wants to fix this it will be happily included :)
