### ISSUE TITLE
Tekkit 2 borderless resolution

### ISSUE THREAD

**Issue by TheAio** [xJon/Tekkit-2#85]
Tekkit 2 borderless resolution behaveing weirdly
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no

When i run tekkit 2 in a window and in a full screen bordered window everything runs fine.

But if i try to run tekkit 2 in a borderless window the window zooms heavily to the top left and spills over to the screen on my right, changing GUI scale to and from auto does not help neither does defining resolution in the technic launcher. I unfortunately have to keep windows scaling at 125% so changing to 100% is not an option. Does anyone know of a solution?

**Comment by TheAio** [comment]
I tried temporarially changeing scaling to 100% and it worked but due to other reasons i cant keep scaling at 100% and need it at 125%

**Comment by xJon** [comment]
Is this an issue in other 1.12 packs? I'm unfamiliar with it unfortunately

**Comment by Jaari** [comment]
Disable display scaling. Right click Javaw.exe in your Java folder, go to "Properties", and under "Compatibility" there will be the option to disable display scaling for high DPI displays.
The only thing to figure out now is if you are using "mojang runtimes" or if you are using your own java (this just changes which javaw.exe you'll have to interact with).

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
