### ISSUE TITLE
IC2 sounds reset after restart

### ISSUE THREAD

**Issue by PawnixHere** [xJon/Tekkit-2#88]
IC2 machine audio resets and defaults back to max volume after a restart of the modpack

**Comment by xJon** [comment]
Are you sure it didn't reset due to the modpack update?

**Comment by PawnixHere** [comment]
I don't think so. I feel like it happens every time I restart the game

**Comment by xJon** [comment]
Can you test/verify it then?

**Comment by PawnixHere** [comment]
I just did. I think it happens after every update.
