### ISSUE TITLE
Possibility of adding WTHIT to Tekkit 2?

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/Tekkit-2#9]
I miss having the block name indicator at the top of the screen like many packs including Tekkit and Tekkit Legends have
![image](https://user-images.githubusercontent.com/48618519/187092353-f78958f5-9aff-4090-b7a1-84271c401197.png)
Any chance of this mod being added?
https://www.curseforge.com/minecraft/mc-mods/wthit-forge

**Comment by xJon** [comment]
It's included but disabled by default! You can press numpad 0 in order to enable it.

**Comment by OpenSauce04** [comment]
Oh! Thanks for the response, I had no idea!
