### ISSUE TITLE
Breaking thermal monitor can crash client

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#90]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: https://mclo.gs/a69VGP0

**Describe the issue**

I just went to remove a thermal monitor and the client crashed in multiplayer, the server is fine.

**Comment by xJon** [comment]
Can you please post this issue over https://github.com/Zuxelus/Energy-Control/issues ?

**Comment by SparksSkywere** [comment]
> 

Done

**Comment by xJon** [comment]
Apart from forwarding the issue to Energy Control there's not much else I can do now as it is not currently in active development. Closing for now :)
