### ISSUE TITLE
[Suggestion] Additional Enchanted Miner(QuarryPlus) 

### ISSUE THREAD

**Issue by Munchy907** [xJon/Tekkit-2#92]
Mod Suggestion:

Additional Enchanted Miner:
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner

Gives buildcraft a extra layer with better version of the machines as well as has it own take on a filler
In general just makes buildcraft more useful in the later game

**Comment by Lumpous** [comment]
The listed mod is not available for 1.12.2 if I read that correctly.

**Comment by ACGaming** [comment]
> The listed mod is not available for 1.12.2 if I read that correctly.

Yes, it is. 🙂

**Comment by Munchy907** [comment]
>
> The listed mod is not available for 1.12.2 if I read that correctly.

https://prnt.sc/pDokpQpicR_s

**Comment by Lumpous** [comment]
You're right - I was looking through the website on my phone and just missed the entry there.
I apologize for that!

**Comment by xJon** [comment]
This is currently not planned at this point, as the mod doesn't really fit the modpack theme, but thank you for the suggestion!
Also to be honest, the Filler is nice and is distinctly missing from BuildCraft, but as both mods are open source it the code could inspire a PR to BuildCraft's repo.
