### ISSUE TITLE
Logistics pipes crashing Server

### ISSUE THREAD

**Issue by Taliviere4586** [xJon/Tekkit-2#97]
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log / not applicable
https://mclo.gs/2L6ITiU

**Describe the issue**
Multiplayer server Crashing Continuously from logistics pipes
A clear description of what the issue is.
Players usually messing with their factory find a pipe full of items and break it then the server crash's or similar instances of teleporting away and too the factory and crashing. I Can supply another crash log if wanted.

**Comment by xJon** [comment]
This crash report just shows the server timed out (whilst generating new chunks, it seems), nothing to do with Logistics Pipes

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
